-- Concurrency-safe idempotent balance-refresh enqueue for confirmed bridges
-- (Phase-2 factory W4 / plan C3, FIX-ROUND-1 Blocker 11).
--
-- The W4 sweep enqueues ONE balance-refresh `protocol_sync_runs` row per
-- confirmed bridge execution, and its C3 recovery path re-enqueues any confirmed
-- row that still lacks one. Before this migration that INSERT was guarded only by
-- an application-level `WHERE NOT EXISTS`, so two concurrent sweeps could both
-- pass the check and duplicate the run. This partial unique index is the DB-level
-- authority the sweep's `ON CONFLICT DO NOTHING` targets: at most one run per
-- (sync job, execution).
--
-- SCOPE / SAFETY: the index is PARTIAL on `execution_id IS NOT NULL`, so it
-- constrains ONLY execution-scoped enqueues (the bridge sweep + the post-mutation
-- capture path, which already enqueue at most once per (job, execution)). Periodic
-- scheduler runs use `execution_id = NULL` and are entirely unaffected — NULLs are
-- excluded from a partial index and never collide. Expand-only + reversible
-- (drop the index to undo); no data is rewritten.
--
-- Mirror note (rule 90): the source of truth is this file; the packaged copy in
-- `vex-app/resources/migrations/` is regenerated by
-- `vex-app/scripts/copy-migrations.mjs` on prebuild/predev.

CREATE UNIQUE INDEX IF NOT EXISTS idx_sync_runs_execution_dedup
  ON protocol_sync_runs (sync_job_id, execution_id)
  WHERE execution_id IS NOT NULL;
