/**
 * The Lighter signer's order-type and time-in-force wire codes, table-tested
 * against the machine artifact rather than against themselves.
 *
 * THE DEFECT THIS PINS. `signer-order.ts` hand-spells the integers it puts on
 * the wire (`limit: 0`, `post-only: 2`, ...). Rule 10 item 2 forbids that
 * exactly because nothing fails when the provider renumbers a member or
 * inserts one: the signer keeps producing a correctly signed order of the
 * WRONG TYPE, the exchange accepts it, and the first evidence is a fill the
 * user did not ask for. A test that re-lists the same numbers by hand would
 * pin the typo, not the contract.
 *
 * THE ARTIFACT. `src/tools/lighter/signer-runtime/wire-constants.json` is
 * generated by `signer-runtime/cmd/wire-constants`, a Go program that IMPORTS
 * `github.com/elliottech/lighter-go/types/txtypes` at the version go.mod pins
 * and prints its constants. So the numbers below come from the same package
 * the signer binary links against - not from documentation, not from a clone,
 * and not from memory. This test deliberately reads only the checked-in
 * artifact: a test that reached into a local reference checkout would pass on
 * one machine and fail in CI, and would pin whatever version that checkout
 * happened to be on rather than the pinned one.
 *
 * BOTH DIRECTIONS, which is what makes it a table test:
 *  - every TypeScript entry resolves to an artifact member with the same code;
 *  - every artifact member is either mapped by TypeScript or named in
 *    `DELIBERATELY_UNSUPPORTED` with the reason, so a NEW provider member
 *    (Lighter adding an order type) fails here and gets a decision.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, it, expect } from "vitest";

import {
  LIGHTER_SIGNER_ORDER_TYPE_CODES,
  LIGHTER_SIGNER_TIME_IN_FORCE_CODES,
} from "@tools/lighter/signer-order.js";

const ARTIFACT_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../../tools/lighter/signer-runtime/wire-constants.json",
);

interface WireConstants {
  readonly source: string;
  readonly generator: string;
  readonly regenerate: string;
  readonly orderTypes: Readonly<Record<string, number>>;
  readonly timeInForce: Readonly<Record<string, number>>;
  readonly apiMaxOrderType: number;
}

const artifact = JSON.parse(readFileSync(ARTIFACT_PATH, "utf8")) as WireConstants;

/**
 * Vex's spelling of each wire member -> the EXPORTED Go identifier in
 * `txtypes`. The Go name is the key in the artifact, so a rename upstream is a
 * missing key here rather than a silently re-pointed value.
 */
const ORDER_TYPE_NAMES: Readonly<Record<keyof typeof LIGHTER_SIGNER_ORDER_TYPE_CODES, string>> = {
  limit: "LimitOrder",
  market: "MarketOrder",
  "stop-loss": "StopLossOrder",
  "stop-loss-limit": "StopLossLimitOrder",
  "take-profit": "TakeProfitOrder",
  "take-profit-limit": "TakeProfitLimitOrder",
};

const TIME_IN_FORCE_NAMES: Readonly<
  Record<keyof typeof LIGHTER_SIGNER_TIME_IN_FORCE_CODES, string>
> = {
  "immediate-or-cancel": "ImmediateOrCancel",
  "good-till-time": "GoodTillTime",
  "post-only": "PostOnly",
};

/**
 * Provider members Vex deliberately does not offer, each with the reason.
 *
 * `TWAPOrder` is a scheduled multi-leg execution: the venue slices it over
 * time and reports sub-orders, which is a different approval, a different
 * reconciliation story and a different set of durable rows from the
 * single-shot orders the create path builds. Adding it is a product decision,
 * not a map entry, so it is named here rather than silently absent.
 */
const DELIBERATELY_UNSUPPORTED: Readonly<Record<string, string>> = {
  TWAPOrder: "scheduled multi-leg execution; a separate approval and reconciliation contract",
};

describe("Lighter signer wire codes match the pinned lighter-go artifact", () => {
  it("was generated from the pinned module, and says how to regenerate itself", () => {
    expect(artifact.source).toContain("github.com/elliottech/lighter-go/types/txtypes");
    expect(artifact.generator).toBe("src/tools/lighter/signer-runtime/cmd/wire-constants");
    expect(artifact.regenerate).toContain("go run ./cmd/wire-constants");
  });

  it.each(
    Object.entries(ORDER_TYPE_NAMES).map(([vexName, goName]) => ({ vexName, goName })),
  )("maps order type $vexName to txtypes.$goName", ({ vexName, goName }) => {
    const code = LIGHTER_SIGNER_ORDER_TYPE_CODES[
      vexName as keyof typeof LIGHTER_SIGNER_ORDER_TYPE_CODES
    ];
    expect(artifact.orderTypes).toHaveProperty(goName);
    expect(code).toBe(artifact.orderTypes[goName]);
  });

  it.each(
    Object.entries(TIME_IN_FORCE_NAMES).map(([vexName, goName]) => ({ vexName, goName })),
  )("maps time in force $vexName to txtypes.$goName", ({ vexName, goName }) => {
    const code = LIGHTER_SIGNER_TIME_IN_FORCE_CODES[
      vexName as keyof typeof LIGHTER_SIGNER_TIME_IN_FORCE_CODES
    ];
    expect(artifact.timeInForce).toHaveProperty(goName);
    expect(code).toBe(artifact.timeInForce[goName]);
  });

  it("accounts for every order type the provider exposes to API clients", () => {
    const mapped = new Set(Object.values(ORDER_TYPE_NAMES));
    const unaccounted = Object.keys(artifact.orderTypes)
      .filter((goName) => !mapped.has(goName) && DELIBERATELY_UNSUPPORTED[goName] === undefined);
    // A NEW provider member lands here. Decide it: add the Vex spelling to
    // `ORDER_TYPE_NAMES`, or record why Vex does not offer it.
    expect(unaccounted).toEqual([]);
  });

  it("accounts for every time in force the provider exposes", () => {
    const mapped = new Set(Object.values(TIME_IN_FORCE_NAMES));
    const unaccounted = Object.keys(artifact.timeInForce).filter((goName) => !mapped.has(goName));
    expect(unaccounted).toEqual([]);
  });

  it("offers no order type above the provider's own API maximum", () => {
    // `ApiMaxOrderType` is lighter-go's statement of where the client-facing
    // surface ends; the internal TWAP sub-order and liquidation types sit above
    // it and must never be reachable from a Vex order.
    for (const code of Object.values(LIGHTER_SIGNER_ORDER_TYPE_CODES)) {
      expect(code).toBeLessThanOrEqual(artifact.apiMaxOrderType);
    }
  });

  it("keeps every wire code a distinct non-negative integer", () => {
    const orderCodes = Object.values(LIGHTER_SIGNER_ORDER_TYPE_CODES);
    const tifCodes = Object.values(LIGHTER_SIGNER_TIME_IN_FORCE_CODES);
    expect(new Set(orderCodes).size).toBe(orderCodes.length);
    expect(new Set(tifCodes).size).toBe(tifCodes.length);
    for (const code of [...orderCodes, ...tifCodes]) {
      expect(Number.isInteger(code)).toBe(true);
      expect(code).toBeGreaterThanOrEqual(0);
    }
  });
});
