import type { ProtocolToolManifest } from "../../types.js";
import { SOLANA_PREDICT_DISCOVERY } from "../../embeddings/solana-jupiter/predict.js";

export const PREDICT_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "solana.predict.events",
    namespace: "solana",
    lifecycle: "active",
    description: "List/browse prediction market events across categories (crypto, sports, politics, culture, economics, tech), with filtering, sorting, and pagination. Use solana.predict.search instead for a keyword lookup, or solana.predict.event for one already-known event by ID. Money field volumeUsd is an exact-decimal USD string with a raw volumeUsdMicro sibling.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "category", type: "string", description: "Category filter: all, crypto, sports, politics, esports, culture, economics, or tech. Omit for all categories." },
      { key: "filter", type: "string", description: "Status filter: trending, live, new, or upcoming (not yet open for trading)." },
      { key: "provider", type: "string", description: "Provider: kalshi, polymarket, or bisonfi (Jupiter Forecast). Default polymarket." },
      { key: "subcategory", type: "string", description: "Comma-separated subcategory filter." },
      { key: "tags", type: "string", description: "Free-text tag filter, e.g. soccer." },
      { key: "sortBy", type: "string", description: "Sort by: volume or beginAt." },
      { key: "sortDirection", type: "string", description: "Sort direction: asc or desc." },
      { key: "includeMarkets", type: "boolean", description: "Include each event's nested markets array (default false — lean; use solana.predict.event for one event's markets)." },
      { key: "limit", type: "number", description: "Max results, 1-100 (default 20)." },
      { key: "offset", type: "number", description: "Skip first N results for pagination." },
    ],
    exampleParams: { category: "crypto", filter: "trending" },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.events"],
  },
  {
    toolId: "solana.predict.search",
    namespace: "solana",
    lifecycle: "active",
    description: "Search prediction events by keyword across all categories and providers — use this to find a SPECIFIC event/topic by name (e.g. \"bitcoin\", \"election\") instead of browsing via solana.predict.events. Once you have a marketId/eventId from the results, use solana.predict.market or solana.predict.event for full detail.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "query", type: "string", required: true, description: "Search keyword or phrase, e.g. \"bitcoin\" or \"super bowl\"." },
      { key: "provider", type: "string", description: "Provider: kalshi, polymarket, or bisonfi (Jupiter Forecast). Default polymarket." },
      { key: "includeMarkets", type: "boolean", description: "Include each event's nested markets array (default false — lean; use solana.predict.event for one event's markets)." },
      { key: "limit", type: "number", description: "Max results, 1-20 (default 20). The provider ignores this param upstream — Vex enforces the requested count locally." },
    ],
    exampleParams: { query: "bitcoin" },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.search"],
  },
  {
    toolId: "solana.predict.market",
    namespace: "solana",
    lifecycle: "active",
    description: "Get full details for ONE known prediction market by ID — YES/NO buy/sell prices, volume, status, payout. Use solana.predict.events/.search first to find a marketId, or solana.predict.orderbook for order-book depth beyond the top-of-book prices returned here. Price fields (buyYesPriceUsd, buyNoPriceUsd, sellYesPriceUsd, sellNoPriceUsd) are exact-decimal USD strings with raw *Micro siblings; volumeUsd is a whole-dollar exact string.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "marketId", type: "string", required: true, description: "Market ID (from solana.predict.events, solana.predict.search, or an event's nested markets)." },
    ],
    exampleParams: { marketId: "abc123" },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.market"],
  },
  {
    toolId: "solana.predict.positions",
    namespace: "solana",
    lifecycle: "active",
    description: "Get a wallet's currently OPEN prediction positions — exposure, unrealized PnL, and claimability, one row per YES/NO side held. Use solana.predict.history instead for PAST (closed/settled) trades. Money fields (sizeUsd, valueUsd, avgPriceUsd, markPriceUsd, pnlUsd, payoutUsd) are exact-decimal USD strings with raw *Micro siblings; prefer contractsMicro/contractsDecimal over the legacy contracts field for exact accounting.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "walletAddress", type: "string", description: "The wallet ACCOUNT to read, as a Solana address (not a token mint or a position key). Defaults to the session's selected Solana wallet — omit it to read your own. Under session scope a DIFFERENT address is rejected." },
      { key: "marketPubkey", type: "string", description: "Filter by on-chain market account." },
      { key: "marketId", type: "string", description: "Filter by external market ID." },
      { key: "isYes", type: "boolean", description: "Filter by side — true for YES, false for NO." },
      { key: "limit", type: "number", description: "Max results, 1-100 (default 20)." },
      { key: "offset", type: "number", description: "Skip first N results for pagination." },
    ],
    exampleParams: {},
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.positions"],
  },
  {
    toolId: "solana.predict.history",
    namespace: "solana",
    lifecycle: "active",
    description: "Get a wallet's PAST (closed/settled) prediction trade history — buys, sells, claims, realized PnL. Use solana.predict.positions instead for currently OPEN positions. Money *Usd fields (realizedPnl, realizedPnlBeforeFees, feeUsd, payoutAmountUsd, etc.) are exact-decimal USD strings with raw *Micro siblings; transferAmountTokenRaw is a SEPARATE unit family — the transferred token's own native units, never a USD amount — do not convert or compare it against the *Usd fields.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "walletAddress", type: "string", description: "The wallet ACCOUNT to read, as a Solana address (not a token mint or a position key). Defaults to the session's selected Solana wallet — omit it to read your own. Under session scope a DIFFERENT address is rejected." },
      { key: "positionPubkey", type: "string", description: "Filter to one position's history." },
      { key: "id", type: "number", description: "Filter to a single history event ID." },
      { key: "limit", type: "number", description: "Max results, 1-100 (default 20)." },
      { key: "offset", type: "number", description: "Skip first N results for pagination." },
    ],
    exampleParams: {},
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.history"],
  },
  {
    toolId: "solana.predict.buy",
    namespace: "solana",
    lifecycle: "active",
    description: "Buy YES or NO shares in a prediction market — opens or adds to a position. Read solana.predict.tradingStatus first to confirm trading is active, and solana.predict.market/.orderbook to check current pricing before sizing amountUsdc. Broadcasts and returns truthful-pending — never confirms in this call; estimatedSizeUsd/estimatedFeeUsd in the output are order-preview ESTIMATES, not executed truth. Use solana.predict.sell to exit before resolution, or solana.predict.claim after the market resolves.",
    mutating: true,
    actionKind: "user_wallet_broadcast",
    params: [
      { key: "marketId", type: "string", required: true, description: "Market ID (from solana.predict.events/.search)." },
      { key: "side", type: "string", required: true, description: "Side: yes or no." },
      { key: "amountUsdc", type: "number", required: true, description: "Amount to spend, in whole/fractional USDC dollars (human-readable, e.g. 10 for $10) — not raw atomic units." },
    ],
    exampleParams: { marketId: "abc123", side: "yes", amountUsdc: 10 },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.buy"],
  },
  {
    toolId: "solana.predict.sell",
    namespace: "solana",
    lifecycle: "active",
    description: "Sell (close) an OPEN prediction position before the market resolves, for whatever it's currently worth. Use solana.predict.claim instead once the market has RESOLVED and this position is a winner — claim settles at the resolved price; a sell takes whatever the book offers and Vex applies the provider's own default tolerance — size the position accordingly. Broadcasts and returns truthful-pending; estimatedPayoutUsd in the output is an order-preview ESTIMATE, not executed truth. Payouts settle in JupUSD (6 decimals), not USDC, and they arrive in a LATER keeper transaction — this call's broadcast does not deliver them, so the position stays pending until settlement is observed. To convert a payout to USDC, run solana.swap.quote/solana.swap.execute with tokenIn JupUSD, tokenOut USDC once the balance appears.",
    mutating: true,
    actionKind: "user_wallet_broadcast",
    params: [
      { key: "positionPubkey", type: "string", required: true, description: "Position public key (from solana.predict.positions)." },
    ],
    exampleParams: { positionPubkey: "Abc123..." },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.sell"],
  },
  {
    toolId: "solana.predict.claim",
    namespace: "solana",
    lifecycle: "active",
    description: "Claim winnings from a RESOLVED (settled) prediction position — the market has an outcome and this position won. Use solana.predict.sell instead to exit an OPEN position before resolution. Broadcasts and returns truthful-pending; estimatedPayoutUsd in the output is an order-preview ESTIMATE, not executed truth. Payouts settle in JupUSD (6 decimals), not USDC, and they arrive in a LATER keeper transaction — this call's broadcast does not deliver them, so the position stays pending until settlement is observed. To convert a payout to USDC, run solana.swap.quote/solana.swap.execute with tokenIn JupUSD, tokenOut USDC once the balance appears.",
    mutating: true,
    actionKind: "user_wallet_broadcast",
    params: [
      { key: "positionPubkey", type: "string", required: true, description: "Position public key (from solana.predict.positions)." },
    ],
    exampleParams: { positionPubkey: "Abc123..." },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.claim"],
  },
  {
    toolId: "solana.predict.closeAll",
    namespace: "solana",
    lifecycle: "active",
    description: "Close every open prediction position for the wallet in one call — each position gets its own independent sell-or-claim (whichever applies) and its own broadcast result; a failure on one position never blocks or rolls back the others. Zero open positions is reported as an explicit success with zero rows, never an error. Every result is truthful-pending — this never confirms any position in this call. Use solana.predict.sell/.claim instead to close just ONE position.",
    mutating: true,
    actionKind: "user_wallet_broadcast",
    params: [
      { key: "minSellPriceSlippageBps", type: "number", unit: "bps", required: true, description: "Slippage tolerance applied to EACH sell in this batch, in basis points (0-1000; e.g. 100 = 1%). Vex caps slippage at 1000 bps (10%) and rejects anything above rather than clamping. Required by the provider — there is no default, so pick a value you accept across every position closed." },
    ],
    exampleParams: { minSellPriceSlippageBps: 100 },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.closeAll"],
  },
  {
    toolId: "solana.predict.event",
    namespace: "solana",
    lifecycle: "active",
    description: "Get ONE known prediction event by ID — pass includeMarkets to also fetch its nested markets (each with its own marketId for solana.predict.market). Use solana.predict.events to browse/list events, or solana.predict.search to find an event by keyword.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "eventId", type: "string", required: true, description: "Event ID (from solana.predict.events or solana.predict.search)." },
      { key: "includeMarkets", type: "boolean", description: "Include the event's nested markets array (default false — lean)." },
    ],
    exampleParams: { eventId: "abc123" },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.event"],
  },
  {
    toolId: "solana.predict.position",
    namespace: "solana",
    lifecycle: "active",
    description: "Get ONE prediction position's full detail by pubkey — open or resolved, contracts, payout, claimability. Use solana.predict.positions to list all of a wallet's open positions and find a pubkey.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "positionPubkey", type: "string", required: true, description: "Position public key (from solana.predict.positions)." },
    ],
    exampleParams: { positionPubkey: "Abc123..." },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.position"],
  },
  // ── Pre-trade visibility & order tools (W1-D) ───────────────────
  {
    toolId: "solana.predict.orderbook",
    namespace: "solana",
    lifecycle: "active",
    description: "Get bid/ask order-book depth for a prediction market — YES/NO price levels and sizes, beyond the top-of-book price solana.predict.market already returns. Depth is uncapped upstream and can be large for liquid markets. Fails with a clear error (never a silent empty book) when Jupiter's own upstream order-book data is temporarily unavailable.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "marketId", type: "string", required: true, description: "Market ID." },
    ],
    exampleParams: { marketId: "abc123" },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.orderbook"],
  },
  {
    toolId: "solana.predict.tradingStatus",
    namespace: "solana",
    lifecycle: "active",
    description: "Check whether Jupiter Prediction Markets trading is currently active — call before placing an order.",
    mutating: false,
    actionKind: "read",
    params: [],
    exampleParams: {},
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.tradingStatus"],
  },
  {
    toolId: "solana.predict.orders",
    namespace: "solana",
    lifecycle: "active",
    description: "List a wallet's prediction orders (buy/sell order lifecycle — pending/filled/failed, distinct from settled positions). No server-side status or market filter exists upstream — results are the owner's orders within the requested page, unfiltered beyond that. Use solana.predict.order or solana.predict.orderStatus for a single order by pubkey.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "walletAddress", type: "string", description: "The wallet ACCOUNT to read, as a Solana address (not a token mint or a position key). Defaults to the session's selected Solana wallet — omit it to read your own. Under session scope a DIFFERENT address is rejected." },
      { key: "limit", type: "number", description: "Max results, 1-100 (default 20)." },
      { key: "offset", type: "number", description: "Skip first N results for pagination." },
    ],
    exampleParams: {},
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.orders"],
  },
  {
    toolId: "solana.predict.order",
    namespace: "solana",
    lifecycle: "active",
    description: "Get a single prediction order by pubkey (from solana.predict.orders). Errors once the order account closes post-fill — use solana.predict.orderStatus instead for a lookup that survives closure.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "orderPubkey", type: "string", required: true, description: "Order public key (from solana.predict.orders)." },
    ],
    exampleParams: { orderPubkey: "Abc123..." },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.order"],
  },
  {
    toolId: "solana.predict.orderStatus",
    namespace: "solana",
    lifecycle: "active",
    description: "Get a prediction order's durable status and fill-event history (from solana.predict.orders) — survives order-account closure, unlike solana.predict.order.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "orderPubkey", type: "string", required: true, description: "Order public key (from solana.predict.orders)." },
    ],
    exampleParams: { orderPubkey: "Abc123..." },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.orderStatus"],
  },
  {
    toolId: "solana.predict.trades",
    namespace: "solana",
    lifecycle: "active",
    description: "Browse the global Jupiter Prediction trade feed (all traders, all markets) — no owner/market scope upstream. Vex applies the requested limit/offset window client-side. Money fields (amountUsd, priceUsd) are exact-decimal USD strings with raw *Micro siblings.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "limit", type: "number", required: true, description: "Max results, 1-100. Required — this feed has no upstream owner/market scope, so an explicit window is required to avoid an unbounded response." },
      { key: "offset", type: "number", description: "Skip first N results for pagination." },
    ],
    exampleParams: { limit: 20 },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.trades"],
  },
  // ── Discovery & social tools (W1-F) ─────────────────────────────
  {
    toolId: "solana.predict.profile",
    namespace: "solana",
    lifecycle: "active",
    description: "Get a trader's aggregate lifetime Jupiter Prediction stats — realized PnL, total volume, win/loss counts. Session-scoped: a walletAddress other than the session's selected wallet is REJECTED, so use solana.predict.leaderboards to compare other traders. Use solana.predict.pnlHistory instead for a PnL time series, or solana.predict.leaderboards to compare against other traders. Money fields (realizedPnlUsd, totalVolumeUsd, totalPositionsValueUsd) are exact-decimal USD strings with raw *Micro siblings.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "walletAddress", type: "string", description: "The wallet ACCOUNT to read, as a Solana address (not a token mint or a position key). Defaults to the session's selected Solana wallet — omit it to read your own. Under session scope a DIFFERENT address is rejected." },
    ],
    exampleParams: {},
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.profile"],
  },
  {
    toolId: "solana.predict.pnlHistory",
    namespace: "solana",
    lifecycle: "active",
    description: "Get a wallet's realized-PnL TIME SERIES on Jupiter Prediction over an interval — use solana.predict.profile instead for a single lifetime snapshot rather than a series. realizedPnlUsd per data point is an exact-decimal USD string with a raw realizedPnlUsdMicro sibling. NOTE: as of 2026-07-24 the provider's pnl-history route is documented but returns 404 upstream for every wallet (a provider-side outage, not removal) — prefer solana.predict.profile until it is restored upstream.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "walletAddress", type: "string", description: "The wallet ACCOUNT to read, as a Solana address (not a token mint or a position key). Defaults to the session's selected Solana wallet — omit it to read your own. Under session scope a DIFFERENT address is rejected." },
      { key: "interval", type: "string", required: true, description: "Interval: 24h, 1w, or 1m." },
      { key: "count", type: "number", description: "Number of data points to return, 1-100 (Vex owner-wide cap; provider default 10 when omitted)." },
    ],
    exampleParams: { interval: "1w" },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.pnlHistory"],
  },
  {
    toolId: "solana.predict.leaderboards",
    namespace: "solana",
    lifecycle: "active",
    description: "Get ranked Jupiter Prediction traders by period and metric (PnL, volume, or win rate) — use solana.predict.profile instead for one trader's own stats rather than a ranked comparison. realizedPnlUsd/totalVolumeUsd fields are exact-decimal USD strings with raw *Micro siblings. Note: each row's winRatePct is unit-unconfirmed (no fixture/doc has confirmed its scale) — treat it as an unverified figure, not a settled percent.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "period", type: "string", required: true, description: "Period: all_time, weekly, or monthly." },
      { key: "metric", type: "string", required: true, description: "Ranking metric: pnl, volume, or win_rate." },
      { key: "limit", type: "number", required: true, description: "Max results, 1-100." },
    ],
    exampleParams: { period: "weekly", metric: "pnl", limit: 10 },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.leaderboards"],
  },
  {
    toolId: "solana.predict.vaultInfo",
    namespace: "solana",
    lifecycle: "active",
    description: "Get the Jupiter Prediction protocol vault's on-chain public key and balance — protocol-level infrastructure state, not a personal wallet or position lookup. Takes no parameters.",
    mutating: false,
    actionKind: "read",
    params: [],
    exampleParams: {},
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.vaultInfo"],
  },
  {
    toolId: "solana.predict.suggestedEvents",
    namespace: "solana",
    lifecycle: "active",
    description: "Get personalized Jupiter Prediction event recommendations for ANY wallet address (not only your own). Use solana.predict.events/.search instead for an unpersonalized browse/keyword lookup.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "walletAddress", type: "string", required: true, description: "The wallet ACCOUNT to base recommendations on, as a Solana address — any wallet, not only your own." },
      { key: "provider", type: "string", description: "Provider: kalshi, polymarket, or bisonfi (Jupiter Forecast). Default polymarket." },
      { key: "includeMarkets", type: "boolean", description: "Include each recommended event's nested markets array (default false — lean)." },
    ],
    exampleParams: { walletAddress: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM" },
    requiresEnv: "JUPITER_API_KEY",
    discovery: SOLANA_PREDICT_DISCOVERY["solana.predict.suggestedEvents"],
  },
];
