/**
 * The `AGENTS.md` MANAGED BLOCK: the only region of that file Vex owns.
 *
 * `AGENTS.md` is the user's file. Vex maintains a fenced region inside it and
 * nothing else:
 *
 *     <!-- vex:studio:begin hash=<16 hex> -->
 *     ...generated body...
 *     <!-- vex:studio:end -->
 *
 * THE HASH IN THE OPENING MARKER IS THE DRIFT CONTRACT. It is the digest of the
 * body Vex wrote. Re-reading the file and re-hashing what is between the markers
 * answers one question exactly: is this still the text Vex generated, or did a
 * human (or another tool) edit inside the fence? A drifted block is REPORTED and
 * left alone; only an explicit Repair overwrites it. That is why the hash lives
 * in the file rather than in a side table: the evidence travels with the bytes,
 * so a project cloned to another machine is still checkable.
 *
 * The body REUSES `STUDIO_SAFETY_PREFIX` from `mcp/instructions.ts` and the
 * extracted `STUDIO_USAGE_NOTES` directly. An agent reading this file and an
 * agent reading the MCP handshake receive the same words, from the same source.
 */

import { createHash } from "node:crypto";

import { STUDIO_SAFETY_PREFIX } from "../../../mcp/instructions.js";
import { STUDIO_USAGE_NOTES } from "../../instructions/shared-usage.js";
import type { StudioRenderResult } from "./facts.js";
import { rendered } from "./facts.js";

const BEGIN_PREFIX = "<!-- vex:studio:begin hash=";
const BEGIN_SUFFIX = " -->";
const END_MARKER = "<!-- vex:studio:end -->";

/** Digest length in hex characters. 16 is 64 bits: ample against accidental collision. */
const HASH_CHARS = 16;

/** Where the rich per-protocol declarations live, relative to the project root. */
export const STUDIO_PROTOCOLS_DOC_PATH = ".vex/protocols.md";

/** The generated body, without the markers. Deterministic and project-independent. */
export function renderStudioManagedBody(): string {
  return [
    "## Vex Studio",
    "",
    "This project is connected to Vex, a self-custodial crypto agent. The Vex",
    "tools reach REAL wallets on REAL chains through the `vex` MCP server.",
    "",
    STUDIO_SAFETY_PREFIX,
    "",
    STUDIO_USAGE_NOTES,
    "",
    `Every protocol, tool and argument contract: \`${STUDIO_PROTOCOLS_DOC_PATH}\`.`,
    "",
    "This section is generated by Vex. Edit it and Vex will report drift and stop",
    "regenerating it until you ask for a repair; text outside the markers is yours.",
  ].join("\n");
}

/** The digest recorded in the opening marker. */
export function studioManagedBodyHash(body: string): string {
  return createHash("sha256").update(body, "utf8").digest("hex").slice(0, HASH_CHARS);
}

/** The complete managed block, markers included, newline-terminated. */
export function renderStudioManagedBlock(): string {
  const body = renderStudioManagedBody();
  return `${BEGIN_PREFIX}${studioManagedBodyHash(body)}${BEGIN_SUFFIX}\n${body}\n${END_MARKER}\n`;
}

/** What an existing `AGENTS.md` currently holds in the Vex fence. */
export type StudioManagedBlockState =
  /** No Vex fence in the file. */
  | { readonly kind: "absent" }
  /** A fence whose body still hashes to the value in its own marker. */
  | { readonly kind: "intact"; readonly upToDate: boolean }
  /**
   * A fence whose body no longer matches its recorded hash: someone edited
   * inside it. Never overwritten except by an explicit Repair.
   */
  | { readonly kind: "drifted"; readonly recordedHash: string; readonly actualHash: string }
  /** An opening marker with no closing marker, or the two in the wrong order. */
  | { readonly kind: "malformed"; readonly detail: string };

export function inspectStudioManagedBlock(existing: string): StudioManagedBlockState {
  const found = locateManagedBlock(existing);
  if (found === undefined) return { kind: "absent" };
  if (typeof found === "string") return { kind: "malformed", detail: found };

  const actualHash = studioManagedBodyHash(found.body);
  if (actualHash !== found.recordedHash) {
    return { kind: "drifted", recordedHash: found.recordedHash, actualHash };
  }
  return { kind: "intact", upToDate: found.body === renderStudioManagedBody() };
}

/**
 * `AGENTS.md` with the Vex block present and current.
 *
 * An absent block is APPENDED; an intact block is replaced in place; a DRIFTED
 * block is left exactly as the user left it unless `overwriteDrift` says this is
 * an explicit Repair. Text outside the fence is never touched.
 */
export function mergeStudioManagedBlock(
  existing: string,
  options: { readonly overwriteDrift: boolean },
): StudioRenderResult {
  const found = locateManagedBlock(existing);
  if (typeof found === "string") {
    // A half-open fence is ambiguous: Vex cannot tell where its region ends, so
    // it refuses rather than guess a boundary inside the user's file.
    return { status: "refused", reason: "malformed_managed_block", detail: found };
  }

  const block = renderStudioManagedBlock();

  if (found === undefined) {
    // Exactly one blank line between the user's text and the Vex fence.
    const separator = existing === ""
      ? ""
      : existing.endsWith("\n\n")
        ? ""
        : existing.endsWith("\n") ? "\n" : "\n\n";
    return rendered(`${existing}${separator}${block}`);
  }

  if (
    !options.overwriteDrift
    && studioManagedBodyHash(found.body) !== found.recordedHash
  ) {
    return { status: "unchanged" };
  }

  const next = `${existing.slice(0, found.start)}${block}${existing.slice(found.end)}`;
  return next === existing ? { status: "unchanged" } : rendered(next);
}

/** `AGENTS.md` with the Vex block removed and every other byte preserved. */
export function removeStudioManagedBlock(existing: string): StudioRenderResult {
  const found = locateManagedBlock(existing);
  if (typeof found === "string") {
    return { status: "refused", reason: "malformed_managed_block", detail: found };
  }
  if (found === undefined) return { status: "unchanged" };
  return rendered(`${existing.slice(0, found.removeStart)}${existing.slice(found.end)}`);
}

interface LocatedBlock {
  /** Offset of the first character of the opening marker. */
  readonly start: number;
  /**
   * Offset where a REMOVE begins: the opening marker, minus the one blank
   * separator line an append inserted before it. That line is part of what Vex
   * added, so removing it returns the file to the bytes it started with. (The
   * one nuance: a file that already had a blank line exactly there before Vex
   * ever touched it loses it. Whitespace at a seam, never content.)
   */
  readonly removeStart: number;
  /** Offset just past the newline that follows the closing marker. */
  readonly end: number;
  readonly recordedHash: string;
  /** The text between the markers, excluding the newlines adjacent to them. */
  readonly body: string;
}

/** The block, `undefined` when absent, or a string naming why it is malformed. */
function locateManagedBlock(existing: string): LocatedBlock | undefined | string {
  const start = existing.indexOf(BEGIN_PREFIX);
  if (start === -1) {
    return existing.includes(END_MARKER)
      ? "a vex:studio:end marker with no matching begin marker"
      : undefined;
  }

  const markerEnd = existing.indexOf(BEGIN_SUFFIX, start + BEGIN_PREFIX.length);
  if (markerEnd === -1) return "the vex:studio:begin marker is not terminated";

  const recordedHash = existing.slice(start + BEGIN_PREFIX.length, markerEnd);
  const bodyStart = markerEnd + BEGIN_SUFFIX.length + 1; // skip the newline
  const endMarker = existing.indexOf(END_MARKER, bodyStart);
  if (endMarker === -1) return "a vex:studio:begin marker with no matching end marker";

  const afterEnd = endMarker + END_MARKER.length;
  const end = existing.charAt(afterEnd) === "\n" ? afterEnd + 1 : afterEnd;

  return {
    start,
    // Reclaim the blank separator line an append inserted before the marker.
    removeStart: existing.slice(0, start).endsWith("\n\n") ? start - 1 : start,
    end,
    recordedHash,
    // The body excludes the newline that precedes the closing marker.
    body: existing.slice(bodyStart, Math.max(bodyStart, endMarker - 1)),
  };
}
