/**
 * `.vex/vex-guide.md`: the SECOND managed document, and the reason there is one.
 *
 * WHAT IT CARRIES. The sections that belong to the Vex protocol but do not have
 * to be in an agent's context on the turn it acts: what changed in Vex, the
 * per-protocol blocks with their chains, fees and provider keys, what an app
 * built on Vex MCP inherits, and how a Vex bug is reported. Each one moved here
 * WHOLE from the `AGENTS.md` managed block on 2026-09-04. Nothing was
 * shortened, summarised or dropped, and `vex-guide.test.ts` proves it by
 * comparing the union of both documents against every section the single block
 * used to compose.
 *
 * WHY IT EXISTS. Codex loads `AGENTS.md` under `project_doc_max_bytes` (32,768
 * by default, `codex-rs/config/defaults.toml`), a TOTAL across the root-to-cwd
 * chain, and TRUNCATES the file that crosses it rather than skipping or
 * splitting it (`codex-rs/core/src/agents_md.rs`). At 36,687 bytes the old
 * block was cut mid-catalogue for every Codex user, silently. There is no
 * include mechanism in `AGENTS.md`, so the fix is the one the official guide
 * names: split the file, and TELL the agent to read the other half. The telling
 * is `STUDIO_READ_ON_START_NOTE`, the first section of the block.
 *
 * HOW IT IS MANAGED. Exactly like the `AGENTS.md` block, through the same fence
 * machinery in `managed-block.ts`: the same begin/end markers, the same digest
 * in the opening marker, the same drift rule, the same repair-only overwrite.
 * The file is Vex's, but the fence is what makes an edit inside it visible
 * rather than silently overwritten, and it lets a user keep notes of their own
 * outside the markers if they want to.
 *
 * NOT `.vex/protocols.md`. That file stays what it is: the generated
 * tool-by-tool inventory, read ON DEMAND, wholly regenerated from the live
 * registry. This one is the guide a session opens with.
 */

import type { StudioInstallationEnvironment } from "../../instructions/installation-environment.js";
import { resolveStudioInstallationEnvironment } from "../../instructions/installation-environment.js";
import type { StudioProjectBrief } from "../../instructions/project-brief.js";
import {
  STUDIO_BUG_REPORT_NOTE,
  STUDIO_BUILDING_APPS_NOTE,
  renderStudioThisFileLog,
  renderStudioWhatsNewInVex,
} from "../../instructions/project-brief.js";
import { renderStudioProtocolBlocks } from "../../instructions/protocol-blocks.js";
import type { StudioRenderResult } from "./facts.js";
import type { StudioManagedBlockState } from "./managed-block.js";
import {
  inspectStudioFencedDocument,
  mergeStudioFencedDocument,
  renderStudioFencedDocument,
} from "./managed-block.js";

/** Where the guide lives, relative to the project root. POSIX. */
export const STUDIO_VEX_GUIDE_PATH = ".vex/vex-guide.md";

/**
 * The guide's body, without the markers.
 *
 * INSTALLATION-DEPENDENT, unlike the `AGENTS.md` block: the protocol blocks
 * report which provider keys THIS machine has, which is a real fact an agent
 * needs before its first call to a gated tool and a real reason for the file to
 * change. The caller states the environment in tests so the goldens do not
 * depend on the machine that ran them; production resolves the live one.
 */
export function renderStudioVexGuideBody(
  brief: StudioProjectBrief,
  environment: StudioInstallationEnvironment = resolveStudioInstallationEnvironment(),
): string {
  return [
    `# Vex guide - project "${brief.projectName}"`,
    "",
    "The companion to this project's `AGENTS.md`, which carries the authority:",
    "the permission level in force, the selected wallets, how to call the tools,",
    "what a result means and the task shapes. READ THIS FILE AT THE START OF A",
    "SESSION - `AGENTS.md` says so in its first section, and everything here is",
    "part of the same protocol.",
    "",
    // 1. What changed, FIRST (Next.js style): in Vex, then in this project.
    //    Two axes under one heading, exactly as they were composed before the
    //    split, down to the `### This file` sub-heading.
    renderStudioWhatsNewInVex(brief),
    "",
    renderStudioThisFileLog(brief),
    "",
    // 2. One block per protocol, with THIS installation's availability.
    renderStudioProtocolBlocks(environment),
    "",
    // 3. Building on the tools.
    STUDIO_BUILDING_APPS_NOTE,
    "",
    // 4. Reporting a Vex bug.
    STUDIO_BUG_REPORT_NOTE,
    "",
    "---",
    "",
    "AGENTS: this file is generated by Vex, between the `vex:studio:begin` and",
    "`vex:studio:end` comment markers. NEVER edit between them, even when asked -",
    "Vex reports the edit as drift and stops regenerating the file until the user",
    "asks Vex for a repair. Text outside the markers belongs to the user.",
  ].join("\n");
}

/** The complete guide, markers included, newline-terminated. */
export function renderStudioVexGuide(
  brief: StudioProjectBrief,
  environment?: StudioInstallationEnvironment,
): string {
  return renderStudioFencedDocument(
    renderStudioVexGuideBody(brief, environment),
    brief.vexVersion,
  );
}

/** The guide file with the Vex fence present and current. */
export function mergeStudioVexGuide(
  existing: string,
  brief: StudioProjectBrief,
  options: {
    readonly overwriteDrift: boolean;
    /**
     * Stated by a test so its bytes do not depend on the machine that ran it;
     * omitted in production, where the live environment is the truth.
     */
    readonly environment?: StudioInstallationEnvironment;
  },
): StudioRenderResult {
  return mergeStudioFencedDocument(
    existing,
    renderStudioVexGuideBody(brief, options.environment),
    brief.vexVersion,
    { overwriteDrift: options.overwriteDrift },
  );
}

/** Is the guide on disk still ours, and still what Vex would write now? */
export function inspectStudioVexGuide(
  existing: string,
  brief: StudioProjectBrief,
  environment?: StudioInstallationEnvironment,
): StudioManagedBlockState {
  return inspectStudioFencedDocument(
    existing,
    renderStudioVexGuideBody(brief, environment),
  );
}
