/**
 * Reasoning replay within the live tool loop (Kairos R-7).
 *
 * WHAT IT IS
 *
 * A reasoning model that calls a tool pauses its answer; the tool result is
 * the continuation of that same answer. OpenRouter returns the model's
 * reasoning as `reasoning_details` (non-streaming: `choices[].message`,
 * streaming: `choices[].delta`) and accepts the array back on the assistant
 * message of a later request: "the entire sequence of consecutive reasoning
 * blocks must match the outputs generated by the model during the original
 * request; you cannot rearrange or modify the sequence of these blocks"
 * (https://openrouter.ai/docs/use-cases/reasoning-tokens, "Preserving
 * Reasoning"). This module captures that array for the rounds of ONE turn-loop
 * run and hands it back on the assistant tool-call messages of the same run.
 *
 * WIRE SHAPE (installed `@openrouter/sdk` 1.1.13)
 *
 * - Request: `ChatAssistantMessage.reasoningDetails` (outbound
 *   `reasoning_details`), `Array<ReasoningDetailUnion>`.
 * - Response: `ChatAssistantMessage.reasoningDetails` (buffered) and
 *   `ChatStreamDelta.reasoningDetails` (streamed fragments).
 * - Members: `reasoning.text` (text, signature), `reasoning.summary`
 *   (summary), `reasoning.encrypted` (data), `reasoning.server_tool_call`
 *   (OpenRouter server tools, which Vex never requests), each with optional
 *   `id`, `format`, `index`. The inbound parser keeps members it does not know
 *   as `{type: "UNKNOWN", raw, isUnknown}`, but the OUTBOUND schema is a closed
 *   union of the four, so an unknown member cannot be sent back at all.
 *
 * SAFETY RULES (each enforced below and pinned by tests)
 *
 * 1. Ships OFF (`REASONING_REPLAY_ENABLED`). OFF captures nothing and the wire
 *    request is byte-identical to the pre-R-7 request.
 * 2. Family allow-list: only model families whose reasoning replay is
 *    documented are ever sent a replay. Everything else gets nothing.
 * 3. All or nothing per round: a round whose details contain anything we
 *    cannot send back faithfully (an unknown member, a server-tool record, an
 *    encrypted block that streamed as `[REDACTED]` or empty, conflicting
 *    fragments for one index, or an oversized payload) is not replayed at all.
 *    A partial sequence would be a MODIFIED sequence, which the docs forbid.
 * 4. Memory only. The payload is an opaque object whose `toJSON` and
 *    `util.inspect` print a count, never the content, so an accidental log
 *    line or JSON dump cannot leak encrypted or raw reasoning. It is never
 *    persisted, never put on a stream-bus delta, and dies with the turn-loop
 *    run that captured it.
 */

import { inspect } from "node:util";

import type { ReasoningDetailUnion } from "@openrouter/sdk/models/reasoningdetailunion.js";
import type { ReasoningDetailText } from "@openrouter/sdk/models/reasoningdetailtext.js";
import type { ReasoningDetailSummary } from "@openrouter/sdk/models/reasoningdetailsummary.js";
import type { ReasoningDetailEncrypted } from "@openrouter/sdk/models/reasoningdetailencrypted.js";

import type { ReasoningReplayPayload } from "../types.js";

/**
 * Switch for the whole feature. `false` (shipped) captures nothing, attaches
 * nothing, and leaves every request byte-identical to the pre-R-7 request.
 */
export const REASONING_REPLAY_ENABLED = false;

/**
 * Model families that may receive a replay, by OpenRouter model-id prefix.
 *
 * Sources:
 * - `anthropic/`: OpenRouter's own "Preserving Reasoning Blocks with
 *   OpenRouter and Claude" example; Anthropic's thinking docs: "when you
 *   return tool results, you must pass the thinking blocks from the assistant
 *   message back to the API, complete and unmodified"
 *   (https://platform.claude.com/docs/en/build-with-claude/thinking).
 * - `openai/`: OpenRouter documents `openai-responses-v1` detail formats and
 *   says replay "works identically" across OpenAI and Anthropic reasoning
 *   models.
 * - `google/`: `google-gemini-v1` is a documented detail format.
 * - `x-ai/`: `xai-responses-v1` is a documented detail format.
 * - `deepseek/`: DeepSeek's thinking-mode docs: with tools, "the
 *   reasoning_content must be fully passed back to the API in all subsequent
 *   requests ... If your code does not correctly pass back reasoning_content,
 *   the API will return a 400 error"
 *   (https://api-docs.deepseek.com/guides/thinking_mode).
 *
 * No family is documented as REJECTING `reasoning_details`; the list is an
 * allow-list anyway, so an undocumented family is never sent one.
 */
const REPLAY_FAMILY_PREFIXES = [
  "anthropic/",
  "openai/",
  "google/",
  "x-ai/",
  "deepseek/",
] as const;

/**
 * Per-round payload cap (UTF-8 bytes of the details' JSON). A round above it
 * is not replayed: it bounds memory and request growth, and a truncated
 * sequence is never an option.
 */
export const MAX_REPLAY_ROUND_BYTES = 512 * 1024;

/** Placeholder OpenRouter documents for encrypted reasoning while streaming. */
const REDACTED_PLACEHOLDER = "[REDACTED]";

export function isReasoningReplayFamily(model: string): boolean {
  return REPLAY_FAMILY_PREFIXES.some((prefix) => model.startsWith(prefix));
}

/**
 * The single gate: the switch is on AND the model's family is allow-listed.
 * Callers pass `REASONING_REPLAY_ENABLED` from their own import, so a test can
 * replace the constant through `vi.mock` (the answer-headroom idiom).
 */
export function shouldReplayReasoning(model: string, enabled: boolean): boolean {
  return enabled && isReasoningReplayFamily(model);
}

/** The members of the SDK union that the outbound schema can send back. */
type ReplayableDetail = ReasoningDetailText | ReasoningDetailSummary | ReasoningDetailEncrypted;

/**
 * Opaque, memory-only carrier of one round's reasoning details.
 *
 * The details sit in a private field; serialisation and inspection print a
 * count only. `detailsForWire` is the one accessor, and the request mapper is
 * its only production caller.
 */
export class OpenRouterReasoningReplay implements ReasoningReplayPayload {
  readonly #details: readonly ReplayableDetail[];
  readonly detailCount: number;
  readonly byteLength: number;

  constructor(details: readonly ReplayableDetail[], byteLength: number) {
    this.#details = details;
    this.detailCount = details.length;
    this.byteLength = byteLength;
  }

  /** Fresh copies, so a caller can never mutate the captured sequence. */
  detailsForWire(): ReasoningDetailUnion[] {
    return this.#details.map((detail) => ({ ...detail }));
  }

  toJSON(): string {
    return `[reasoning replay: ${this.detailCount} details]`;
  }

  [inspect.custom](): string {
    return this.toJSON();
  }
}

/** Replay payload of a provider message, when it is ours and non-empty. */
export function replayDetailsOf(
  payload: ReasoningReplayPayload | undefined,
): ReasoningDetailUnion[] | null {
  if (!(payload instanceof OpenRouterReasoningReplay)) return null;
  if (payload.detailCount === 0) return null;
  return payload.detailsForWire();
}

function isNonEmptyString(value: string | null | undefined): value is string {
  return typeof value === "string" && value.length > 0;
}

/** Validate a finished sequence and wrap it, or `null` when not replayable. */
function seal(details: readonly ReplayableDetail[]): OpenRouterReasoningReplay | null {
  if (details.length === 0) return null;
  for (const detail of details) {
    switch (detail.type) {
      case "reasoning.encrypted":
        if (!isNonEmptyString(detail.data) || detail.data === REDACTED_PLACEHOLDER) return null;
        break;
      case "reasoning.text":
        if (!isNonEmptyString(detail.text) && !isNonEmptyString(detail.signature)) return null;
        break;
      case "reasoning.summary":
        if (!isNonEmptyString(detail.summary)) return null;
        break;
    }
  }
  const byteLength = Buffer.byteLength(JSON.stringify(details), "utf8");
  if (byteLength > MAX_REPLAY_ROUND_BYTES) return null;
  return new OpenRouterReasoningReplay(details, byteLength);
}

/** Narrow one SDK member to a replayable one, or `null` (unknown, server tool). */
function asReplayable(detail: ReasoningDetailUnion): ReplayableDetail | null {
  switch (detail.type) {
    case "reasoning.text":
    case "reasoning.summary":
    case "reasoning.encrypted":
      return detail;
    default:
      return null;
  }
}

/**
 * A COMPLETE details array (buffered response) as a replay payload, or `null`.
 * Kept verbatim: the buffered response already carries one member per block.
 */
export function replayFromCompleteDetails(
  details: readonly ReasoningDetailUnion[] | undefined,
): OpenRouterReasoningReplay | null {
  if (details === undefined || details.length === 0) return null;
  const replayable: ReplayableDetail[] = [];
  for (const detail of details) {
    const narrowed = asReplayable(detail);
    if (narrowed === null) return null;
    replayable.push(narrowed);
  }
  return seal(replayable);
}

function concatText(
  left: string | null | undefined,
  right: string | null | undefined,
): string | null | undefined {
  if (!isNonEmptyString(right)) return left;
  if (!isNonEmptyString(left)) return right;
  return left + right;
}

function lastNonEmpty(
  current: string | null | undefined,
  next: string | null | undefined,
): string | null | undefined {
  return isNonEmptyString(next) ? next : current;
}

/**
 * Merge a later fragment of the SAME block into the accumulated one, or
 * `null` when the two cannot be one block (different type, or two different
 * encrypted payloads for one index).
 */
function mergeFragment(base: ReplayableDetail, next: ReplayableDetail): ReplayableDetail | null {
  if (base.type === "reasoning.text" && next.type === "reasoning.text") {
    return {
      ...base,
      text: concatText(base.text, next.text),
      signature: lastNonEmpty(base.signature, next.signature),
      id: base.id ?? next.id,
      format: base.format ?? next.format,
    };
  }
  if (base.type === "reasoning.summary" && next.type === "reasoning.summary") {
    return {
      ...base,
      summary: (base.summary ?? "") + (next.summary ?? ""),
      id: base.id ?? next.id,
      format: base.format ?? next.format,
    };
  }
  if (base.type === "reasoning.encrypted" && next.type === "reasoning.encrypted") {
    if (!isNonEmptyString(next.data) || next.data === base.data) return base;
    if (!isNonEmptyString(base.data) || base.data === REDACTED_PLACEHOLDER) {
      return { ...base, data: next.data, id: base.id ?? next.id, format: base.format ?? next.format };
    }
    return null;
  }
  return null;
}

/**
 * Accumulates streamed `reasoning_details` fragments into the block sequence.
 *
 * OpenRouter streams a block as several fragments sharing one `index` (text
 * arrives in pieces; a signature can arrive on a later fragment), and says
 * "the complete reasoning sequence is built by concatenating all chunks in
 * order". Fragments with the same `index` are merged into one block, in the
 * order the blocks first appeared; a fragment with no `index` is its own
 * block. Anything the merge cannot represent faithfully poisons the round.
 */
export class ReasoningDetailsAccumulator {
  readonly #blocks: ReplayableDetail[] = [];
  readonly #byIndex = new Map<number, number>();
  #poisoned = false;
  #seen = false;

  add(fragments: readonly ReasoningDetailUnion[] | undefined): void {
    if (fragments === undefined || this.#poisoned) return;
    for (const fragment of fragments) {
      this.#seen = true;
      const detail = asReplayable(fragment);
      if (detail === null) {
        this.#poisoned = true;
        return;
      }
      const index = detail.index;
      if (typeof index !== "number") {
        this.#blocks.push(detail);
        continue;
      }
      const at = this.#byIndex.get(index);
      if (at === undefined) {
        this.#byIndex.set(index, this.#blocks.length);
        this.#blocks.push(detail);
        continue;
      }
      const base = this.#blocks[at];
      const merged = base === undefined ? null : mergeFragment(base, detail);
      if (merged === null) {
        this.#poisoned = true;
        return;
      }
      this.#blocks[at] = merged;
    }
  }

  /** True once any fragment arrived (replayable or not). */
  get sawDetails(): boolean {
    return this.#seen;
  }

  /** The sealed payload, or `null` when nothing arrived or the round is poisoned. */
  finish(): OpenRouterReasoningReplay | null {
    if (this.#poisoned) return null;
    return seal(this.#blocks);
  }
}
