/**
 * Integration: migration 096 applies cleanly to a schema that stops at 095, and
 * its CHECKs accept and reject the rows they are meant to.
 *
 * WHY THIS EXISTS, sibling of `094-pools-launch-attribution.int.test.ts`.
 * `globalSetup` runs the whole chain 001..096 in one pass on an empty database,
 * which proves the file is valid SQL and nothing more. It does NOT prove:
 *
 *   1. that none of 096's objects already exist at 095 - a collision with a
 *      concurrent branch would show up here and nowhere else;
 *   2. that the runner applies 096 as an INCREMENT to a populated schema rather
 *      than as step 96 of a fresh chain;
 *   3. that the table's own CHECK constraints admit exactly the rows the wrap
 *      lifecycle produces and refuse the rest.
 *
 * MECHANISM, unchanged from the 094 template: a second database inside the SAME
 * container the suite already runs, the real `runMigrationsWithProgress`
 * pointed at a temp directory holding only the files at or below 095, and then
 * 096 copied in and the runner invoked again. Nothing is stubbed: same runner,
 * same files, same Postgres.
 *
 * WHICH DIRECTORY THE FILES COME FROM, stated precisely because an earlier
 * revision of this docblock claimed the wrong one. `getVexAgentMigrationsDir()`
 * resolves the directory THE ENGINE RUNTIME ITSELF loads migrations from:
 * `dist/vex-agent/db/migrations` when the package has been built, otherwise the
 * canonical source tree `src/vex-agent/db/migrations` (see
 * `src/utils/package-assets.ts`). It is NOT the desktop app's packaged mirror.
 * That mirror is `vex-app/resources/migrations/`, a git-ignored artifact
 * generated by `vex-app/scripts/copy-migrations.mjs` (wired as vex-app's
 * `prebuild`/`predev`) and packed by electron-builder's `extraResources`.
 *
 * The mirror IS exercised, by the last describe in this file, but only when it
 * exists: a dev checkout that has never run a vex-app build or `dev` has no
 * mirror at all, and a test suite that required an ungenerated artifact would
 * fail for the wrong reason. That describe is therefore gated with the repo's
 * existing `describe.skipIf` idiom and names its remedy in its own title, so a
 * skip is visible in the reporter rather than silent.
 *
 * DELIBERATE DEVIATION on the CHECK half. The sibling unit suites evaluate a
 * constraint body with `db/repos/_sql-check-eval.ts` against concrete rows.
 * That evaluator's grammar is `IS [NOT] NULL`, `=`, `<>` and `IN` over plain
 * columns - it models neither the `payload_json ->> 'key'` extraction nor the
 * `LIKE` prefix match that 096's direction/payload and payload/target
 * constraints are written in, and widening it for one caller would put a second
 * partial SQL implementation in the test tree. So the constraints are evaluated
 * HERE by the authority itself: every row below is a real INSERT against a real
 * PostgreSQL that has migration 096 applied, and "would Postgres accept this
 * row?" is answered by Postgres. That is strictly stronger than the evaluator,
 * not weaker.
 */

import { describe, it, expect, afterAll, beforeAll } from "vitest";
import { copyFileSync, existsSync, mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import pg from "pg";

import { runMigrationsWithProgress } from "../../../lib/db/migrate-runner.js";
import { getPackageRoot, getVexAgentMigrationsDir } from "@utils/package-assets.js";

/** What the ENGINE runtime loads: `dist/` when built, else the source tree. */
const SOURCE_DIR = getVexAgentMigrationsDir();
/** What the DESKTOP APP ships: generated, git-ignored, absent until built. */
const MIRROR_DIR = path.join(getPackageRoot(), "vex-app", "resources", "migrations");
const TARGET_DB = "vex_096_probe";
const MIRROR_DB = "vex_096_mirror";
const MIGRATION_096 = "096_wallet_wrap_intents.sql";
const MIRROR_PRESENT = existsSync(path.join(MIRROR_DIR, MIGRATION_096));

const SESSION = "session-096-probe";
const WALLET = "0xaaaabbbbccccddddeeeeffff0000111122223333";
const WETH = "0x4200000000000000000000000000000000000006";
const OTHER_CONTRACT = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2";
const AMOUNT_RAW = "2500000000000000000";
const DEPOSIT_SELECTOR = "0xd0e30db0";
const WITHDRAW_CALLDATA = `0x2e1a7d4d${BigInt(AMOUNT_RAW).toString(16).padStart(64, "0")}`;
const TX_HASH = "0xaaaa000000000000000000000000000000000000000000000000000000000001";
const DIGEST = "d".repeat(64);

let pool: pg.Pool;
let stagingDir: string;

/**
 * Migration filenames at or below `maxVersion`, in application order. The
 * filter is the runner's own discovery rule, and the same one
 * `copy-migrations.mjs` mirrors with.
 */
function filesUpToIn(dir: string, maxVersion: number): string[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".sql") && /^\d{3}_/.test(f))
    .filter((f) => parseInt(f.slice(0, 3), 10) <= maxVersion)
    .sort();
}

function filesUpTo(maxVersion: number): string[] {
  return filesUpToIn(SOURCE_DIR, maxVersion);
}

function stage(files: readonly string[]): void {
  for (const f of files) copyFileSync(path.join(SOURCE_DIR, f), path.join(stagingDir, f));
}

/**
 * The single row a one-row probe query must have returned. A throwing accessor
 * rather than a non-null assertion: "the catalog query matched nothing" is
 * itself a meaningful failure here and should be named.
 */
function onlyRow<T extends pg.QueryResultRow>(result: pg.QueryResult<T>, what: string): T {
  const row = result.rows[0];
  if (row === undefined) throw new Error(`expected exactly one row for ${what}, got none`);
  return row;
}

async function constraintNames(target: pg.Pool = pool): Promise<string[]> {
  const res = await target.query<{ conname: string }>(
    `SELECT conname FROM pg_constraint
      WHERE conrelid = 'wallet_wrap_intents'::regclass AND contype = 'c'`,
  );
  return res.rows.map((r) => r.conname);
}

interface IntentRow {
  readonly direction: "wrap" | "unwrap";
  readonly wrappedNativeAddress: string;
  readonly amountRaw: string;
  readonly payload: Record<string, string>;
  readonly status: string;
  readonly failureStage: string | null;
  readonly txHash: string | null;
}

/** A VALID wrap row, in every field the CHECKs read. Overridden per case. */
function validWrap(overrides: Partial<IntentRow> = {}): IntentRow {
  return {
    direction: "wrap",
    wrappedNativeAddress: WETH,
    amountRaw: AMOUNT_RAW,
    payload: { to: WETH, data: DEPOSIT_SELECTOR, valueWei: AMOUNT_RAW },
    status: "pending",
    failureStage: null,
    txHash: null,
    ...overrides,
  };
}

/** A VALID unwrap row: the amount is in the calldata and the value is zero. */
function validUnwrap(overrides: Partial<IntentRow> = {}): IntentRow {
  return validWrap({
    direction: "unwrap",
    payload: { to: WETH, data: WITHDRAW_CALLDATA, valueWei: "0" },
    ...overrides,
  });
}

let nextId = 0;

/** Insert one row. Resolves on acceptance, rejects with Postgres's own error. */
async function insertIntent(row: IntentRow, target: pg.Pool = pool): Promise<void> {
  nextId += 1;
  await target.query(
    `INSERT INTO wallet_wrap_intents (
       intent_id, session_id, wallet_address, chain_alias, chain_id, direction,
       wrapped_native_address, wrapped_native_symbol, wrapped_native_decimals,
       amount_raw, payload_json, preview_json, fee_bounds_json,
       proposal_digest, proposal_digest_version,
       status, failure_stage, tx_hash, expires_at
     ) VALUES (
       $1, $2, $3, 'base', 8453, $4,
       $5, 'WETH', 18,
       $6, $7::jsonb, $8::jsonb, $9::jsonb,
       $10, 'v1',
       $11, $12, $13, NOW() + INTERVAL '10 minutes'
     )`,
    [
      `wrp-096-${nextId}`,
      SESSION,
      WALLET,
      row.direction,
      row.wrappedNativeAddress,
      row.amountRaw,
      JSON.stringify(row.payload),
      JSON.stringify({ label: "Wrap 2.5 ETH", criticalArgs: { chain: "base" } }),
      JSON.stringify({
        mode: "eip1559",
        gasLimit: "60000",
        maxFeePerGasWei: "2000000000",
        maxPriorityFeePerGasWei: "1000000000",
        maxTotalFeeWei: "120000000000000",
      }),
      DIGEST,
      row.status,
      row.failureStage,
      row.txHash,
    ],
  );
}

/** The row is accepted. */
async function expectAccepted(row: IntentRow, target: pg.Pool = pool): Promise<void> {
  await expect(insertIntent(row, target)).resolves.toBeUndefined();
}

/** The row is refused by a CHECK, and by a CHECK specifically (SQLSTATE 23514). */
async function expectRejected(row: IntentRow, target: pg.Pool = pool): Promise<void> {
  const error = await insertIntent(row, target).then(
    () => null,
    (err: unknown) => err,
  );
  expect(error, "the row was ACCEPTED but must be refused").not.toBeNull();
  expect((error as { code?: string }).code, "must be a CHECK violation").toBe("23514");
}

beforeAll(async () => {
  const base = process.env.VEX_DB_URL;
  if (!base) throw new Error("VEX_DB_URL is unset - globalSetup did not run.");

  const admin = new pg.Pool({ connectionString: base });
  try {
    await admin.query(`DROP DATABASE IF EXISTS ${TARGET_DB}`);
    await admin.query(`CREATE DATABASE ${TARGET_DB}`);
  } finally {
    await admin.end();
  }

  const url = new URL(base);
  url.pathname = `/${TARGET_DB}`;
  pool = new pg.Pool({ connectionString: url.toString() });

  stagingDir = mkdtempSync(path.join(tmpdir(), "vex-096-"));
}, 120_000);

afterAll(async () => {
  await pool?.end();
  if (stagingDir) rmSync(stagingDir, { recursive: true, force: true });
  const base = process.env.VEX_DB_URL;
  if (base) {
    const admin = new pg.Pool({ connectionString: base });
    try {
      await admin.query(`DROP DATABASE IF EXISTS ${TARGET_DB}`);
    } finally {
      await admin.end();
    }
  }
});

describe("096 applies to a populated schema at 095", () => {
  it("reaches 095 with none of 096's objects present", async () => {
    stage(filesUpTo(95));
    const result = await runMigrationsWithProgress({ pool, migrationsDir: stagingDir });
    expect(result.applied).toBe(filesUpTo(95).length);

    const version = await pool.query<{ v: number }>(
      `SELECT COALESCE(MAX(version), 0)::int AS v FROM schema_version`,
    );
    expect(onlyRow(version, "schema_version high-water mark").v).toBe(95);

    // The table and its indexes must not pre-exist, or 096 is redefining
    // somebody else's object rather than adding its own.
    const table = await pool.query<{ n: string }>(
      `SELECT COUNT(*)::text AS n FROM pg_tables
        WHERE schemaname = 'public' AND tablename = 'wallet_wrap_intents'`,
    );
    expect(Number(onlyRow(table, "the wallet_wrap_intents table").n)).toBe(0);
  });

  it("096 applies as a single increment over a populated schema", async () => {
    // A session and a generic transaction intent, written at the 095 schema:
    // exactly what a real installation holds when 096 arrives. The session is
    // also the FK target every wrap intent below needs.
    await pool.query(`INSERT INTO sessions (id) VALUES ($1)`, [SESSION]);

    copyFileSync(path.join(SOURCE_DIR, MIGRATION_096), path.join(stagingDir, MIGRATION_096));
    const result = await runMigrationsWithProgress({ pool, migrationsDir: stagingDir });

    expect(result.applied).toBe(1);
    expect(result.files).toEqual([MIGRATION_096]);
  });

  it("creates the table with its four named CHECKs and its five indexes", async () => {
    expect(await constraintNames()).toEqual(
      expect.arrayContaining([
        "wallet_wrap_intents_direction_payload",
        "wallet_wrap_intents_payload_target",
        "wallet_wrap_intents_failure_stage",
        "wallet_wrap_intents_evidence",
        "wallet_wrap_intents_failed_evidence",
      ]),
    );

    const indexes = await pool.query<{ indexname: string }>(
      `SELECT indexname FROM pg_indexes WHERE tablename = 'wallet_wrap_intents'`,
    );
    expect(indexes.rows.map((r) => r.indexname)).toEqual(
      expect.arrayContaining([
        "idx_wallet_wrap_intents_session",
        "idx_wallet_wrap_intents_status_expires",
        "idx_wallet_wrap_intents_unconfirmed",
        "idx_wallet_wrap_intents_activity",
        "idx_wallet_wrap_intents_activity_unique",
      ]),
    );
  });

  it("has NO fee column of any kind - the absence is the design", async () => {
    const columns = await pool.query<{ column_name: string }>(
      `SELECT column_name FROM information_schema.columns
        WHERE table_name = 'wallet_wrap_intents'`,
    );
    const names = columns.rows.map((r) => r.column_name);
    expect(names.filter((n) => n.includes("fee") && n !== "fee_bounds_json")).toEqual([]);
    // Nor a price surface: the contract converts 1:1, so there is nothing to
    // be filled worse than.
    for (const absent of ["slippage_bps", "min_out_raw", "recipient", "route_json"]) {
      expect(names).not.toContain(absent);
    }
  });

  it("re-running the chain is a no-op - 096 is not re-applied", async () => {
    const result = await runMigrationsWithProgress({ pool, migrationsDir: stagingDir });
    expect(result.applied).toBe(0);
  });
});

describe("096 direction/payload CHECK", () => {
  it("accepts a wrap whose value IS the amount, and an unwrap whose value is zero", async () => {
    await expectAccepted(validWrap());
    await expectAccepted(validUnwrap());
  });

  it("rejects a wrap whose payload valueWei DIFFERS from amount_raw", async () => {
    // `deposit()` credits exactly the transaction's value. A payload that
    // carried a different one would sign a different quantity than the row -
    // and than the digest and the approval card - describe.
    await expectRejected(
      validWrap({ payload: { to: WETH, data: DEPOSIT_SELECTOR, valueWei: "2500000000000000001" } }),
    );
    await expectRejected(
      validWrap({ payload: { to: WETH, data: DEPOSIT_SELECTOR, valueWei: "0" } }),
    );
  });

  it("rejects an unwrap carrying a NON-ZERO value", async () => {
    // `withdraw(uint256)` sends no value. A row that did would move native
    // funds into the wrapper on top of the burn, silently.
    await expectRejected(
      validUnwrap({ payload: { to: WETH, data: WITHDRAW_CALLDATA, valueWei: "1" } }),
    );
    await expectRejected(
      validUnwrap({ payload: { to: WETH, data: WITHDRAW_CALLDATA, valueWei: AMOUNT_RAW } }),
    );
  });

  it("rejects a payload whose selector does not match its direction", async () => {
    await expectRejected(
      validWrap({ payload: { to: WETH, data: WITHDRAW_CALLDATA, valueWei: AMOUNT_RAW } }),
    );
    await expectRejected(
      validUnwrap({ payload: { to: WETH, data: DEPOSIT_SELECTOR, valueWei: "0" } }),
    );
  });
});

describe("096 payload/target CHECK", () => {
  it("rejects a payload whose `to` is not the bound wrapped_native_address", async () => {
    // The transaction is always sent TO the contract the human approved. A
    // payload aimed anywhere else is a different transaction wearing this
    // row's approval.
    await expectRejected(
      validWrap({ payload: { to: OTHER_CONTRACT, data: DEPOSIT_SELECTOR, valueWei: AMOUNT_RAW } }),
    );
    await expectRejected(
      validUnwrap({ payload: { to: OTHER_CONTRACT, data: WITHDRAW_CALLDATA, valueWei: "0" } }),
    );
  });

  it("follows the BOUND address, not the constant - a row for another wrapper is consistent", async () => {
    // Proof the constraint compares two columns rather than pinning one
    // address: a row whose bound contract and payload target are both the
    // other wrapper is accepted.
    await expectAccepted(
      validWrap({
        wrappedNativeAddress: OTHER_CONTRACT,
        payload: { to: OTHER_CONTRACT, data: DEPOSIT_SELECTOR, valueWei: AMOUNT_RAW },
      }),
    );
  });
});

describe("096 amount_raw CHECK", () => {
  it("rejects zero and every non-digit shape", async () => {
    // Rule 90: raw base units, decimal digits, positive. A wrap of zero is not
    // a transaction, a leading zero is not a canonical amount, and anything
    // that had passed through a float would arrive here in exponent form.
    for (const amount of ["0", "0000", "01", "-1", "2.5", "2500000000000000000e0", "1_000", ""]) {
      await expectRejected(
        validWrap({
          amountRaw: amount,
          payload: { to: WETH, data: DEPOSIT_SELECTOR, valueWei: amount },
        }),
      );
    }
  });

  it("accepts a value far beyond BIGINT, which is why the column is TEXT", async () => {
    const huge = (2n ** 200n).toString();
    await expectAccepted(
      validWrap({
        amountRaw: huge,
        payload: { to: WETH, data: DEPOSIT_SELECTOR, valueWei: huge },
      }),
    );
  });
});

describe("096 evidence CHECK - part 1, the statuses that are not `failed`", () => {
  it("rejects a `pending` row that carries a tx hash", async () => {
    // A hash claims a broadcast that cannot have happened yet: staging strictly
    // precedes broadcast, and a pending row has not been staged.
    await expectRejected(validWrap({ status: "pending", txHash: TX_HASH }));
    await expectRejected(validWrap({ status: "consuming", txHash: TX_HASH }));
    await expectRejected(validWrap({ status: "cancelled", txHash: TX_HASH }));
    await expectRejected(validWrap({ status: "expired", txHash: TX_HASH }));
    // `audit_failed` with a hash would mean something WAS signed.
    await expectRejected(validWrap({ status: "audit_failed", txHash: TX_HASH }));
  });

  it("rejects an `executed` row with NO tx hash", async () => {
    // Success it cannot prove. Same for the two other hash-bearing statuses.
    await expectRejected(validWrap({ status: "executed", txHash: null }));
    await expectRejected(validWrap({ status: "broadcast_unconfirmed", txHash: null }));
    await expectRejected(validWrap({ status: "superseded_unproven", txHash: null }));
  });

  it("accepts each status in the shape its lifecycle actually produces", async () => {
    for (const status of ["pending", "consuming", "cancelled", "expired", "audit_failed"]) {
      await expectAccepted(validWrap({ status, txHash: null }));
    }
    for (const status of ["executed", "broadcast_unconfirmed", "superseded_unproven"]) {
      await expectAccepted(validWrap({ status, txHash: TX_HASH }));
    }
  });

  /**
   * `review_required` is the wrap table's own status: the transaction CONFIRMED
   * and its receipt proved a quantity that CONTRADICTS the approved amount. A
   * real transaction exists, so it groups with the hash-BEARING statuses -
   * exactly as migration 093 did for `wallet_intents`.
   */
  it("accepts `review_required` WITH a hash and rejects it without one", async () => {
    await expectAccepted(validWrap({ status: "review_required", txHash: TX_HASH }));
    await expectRejected(validWrap({ status: "review_required", txHash: null }));
  });

  it("rejects `review_required` carrying a failure stage", async () => {
    // It is not a `failed` row: the funds moved. A stage here would claim a
    // failure mode the row does not have.
    await expectRejected(
      validWrap({ status: "review_required", txHash: TX_HASH, failureStage: "chain_reverted" }),
    );
  });
});

describe("096 evidence CHECK - part 2, `failed` splits by stage", () => {
  it("rejects a `failed` row whose stage and hash disagree", async () => {
    // A chain revert is a real transaction and MUST carry the hash the operator
    // reads the receipt from.
    await expectRejected(
      validWrap({ status: "failed", failureStage: "chain_reverted", txHash: null }),
    );
    // A pre-broadcast failure and a crash before broadcast MUST NOT carry one:
    // a failure with a hash is indistinguishable from a revert, and a caller
    // who reads "failed" retries.
    await expectRejected(
      validWrap({ status: "failed", failureStage: "pre_broadcast", txHash: TX_HASH }),
    );
    await expectRejected(
      validWrap({ status: "failed", failureStage: "crashed_before_broadcast", txHash: TX_HASH }),
    );
  });

  it("accepts each `failed` shape the lifecycle writes", async () => {
    await expectAccepted(
      validWrap({ status: "failed", failureStage: "chain_reverted", txHash: TX_HASH }),
    );
    await expectAccepted(
      validWrap({ status: "failed", failureStage: "pre_broadcast", txHash: null }),
    );
    await expectAccepted(
      validWrap({ status: "failed", failureStage: "crashed_before_broadcast", txHash: null }),
    );
  });

  it("rejects a `failed` row with no stage, and any other status WITH one", async () => {
    await expectRejected(validWrap({ status: "failed", failureStage: null, txHash: null }));
    await expectRejected(
      validWrap({ status: "executed", failureStage: "chain_reverted", txHash: TX_HASH }),
    );
  });
});

/**
 * The everything-above ran the ENGINE's migration directory. This runs the
 * DESKTOP APP's packaged mirror: the exact bytes electron-builder packs, staged
 * and applied by the same runner into their own database.
 *
 * The mirror is generated, not committed (`vex-app/.gitignore` ignores
 * `resources/migrations/`), so a checkout that has never run a vex-app build
 * simply does not have it. Gating on its presence rather than generating it
 * from inside a test keeps the artifact's one owner - `copy-migrations.mjs`,
 * run from vex-app's `prebuild`/`predev` - and keeps this suite from depending
 * on an artifact it would have to build itself. The remedy is in the title so
 * the skip is legible in the reporter.
 */
describe.skipIf(!MIRROR_PRESENT)(
  "096 from the PACKAGED MIRROR (vex-app/resources/migrations; generate with `node vex-app/scripts/copy-migrations.mjs`)",
  () => {
    let mirrorPool: pg.Pool;
    let mirrorStagingDir: string;

    beforeAll(async () => {
      const base = process.env.VEX_DB_URL;
      if (!base) throw new Error("VEX_DB_URL is unset - globalSetup did not run.");

      const admin = new pg.Pool({ connectionString: base });
      try {
        await admin.query(`DROP DATABASE IF EXISTS ${MIRROR_DB}`);
        await admin.query(`CREATE DATABASE ${MIRROR_DB}`);
      } finally {
        await admin.end();
      }

      const url = new URL(base);
      url.pathname = `/${MIRROR_DB}`;
      mirrorPool = new pg.Pool({ connectionString: url.toString() });
      mirrorStagingDir = mkdtempSync(path.join(tmpdir(), "vex-096-mirror-"));
    }, 120_000);

    afterAll(async () => {
      await mirrorPool?.end();
      if (mirrorStagingDir) rmSync(mirrorStagingDir, { recursive: true, force: true });
      const base = process.env.VEX_DB_URL;
      if (base) {
        const admin = new pg.Pool({ connectionString: base });
        try {
          await admin.query(`DROP DATABASE IF EXISTS ${MIRROR_DB}`);
        } finally {
          await admin.end();
        }
      }
    });

    it("mirrors 096 byte-for-byte from the source of truth", () => {
      // If this diverges, the packaged app applies different DDL than the
      // engine does, which is the whole failure mode the mirror can have.
      expect(readFileSync(path.join(MIRROR_DIR, MIGRATION_096), "utf8")).toBe(
        readFileSync(path.join(SOURCE_DIR, MIGRATION_096), "utf8"),
      );
    });

    it("applies the mirror's 096 as an increment over a mirror-built 095 schema", async () => {
      const upTo95 = filesUpToIn(MIRROR_DIR, 95);
      // The mirror is not allowed to be a partial copy either: whatever the
      // engine has at or below 095, the shipped artifact has too.
      expect(upTo95).toEqual(filesUpTo(95));

      for (const f of upTo95) {
        copyFileSync(path.join(MIRROR_DIR, f), path.join(mirrorStagingDir, f));
      }
      const at95 = await runMigrationsWithProgress({
        pool: mirrorPool,
        migrationsDir: mirrorStagingDir,
      });
      expect(at95.applied).toBe(upTo95.length);

      await mirrorPool.query(`INSERT INTO sessions (id) VALUES ($1)`, [SESSION]);

      copyFileSync(
        path.join(MIRROR_DIR, MIGRATION_096),
        path.join(mirrorStagingDir, MIGRATION_096),
      );
      const applied = await runMigrationsWithProgress({
        pool: mirrorPool,
        migrationsDir: mirrorStagingDir,
      });
      expect(applied.applied).toBe(1);
      expect(applied.files).toEqual([MIGRATION_096]);
    });

    it("produces the same guarded table in the packaged app's database", async () => {
      expect(await constraintNames(mirrorPool)).toEqual(
        expect.arrayContaining([
          "wallet_wrap_intents_direction_payload",
          "wallet_wrap_intents_payload_target",
          "wallet_wrap_intents_failure_stage",
          "wallet_wrap_intents_evidence",
          "wallet_wrap_intents_failed_evidence",
        ]),
      );

      // One accepted row and one refused row, so this proves the constraints
      // are ENFORCED here and not merely named.
      await expectAccepted(validWrap(), mirrorPool);
      await expectRejected(
        validWrap({ payload: { to: OTHER_CONTRACT, data: DEPOSIT_SELECTOR, valueWei: AMOUNT_RAW } }),
        mirrorPool,
      );
    });
  },
);
