/**
 * Integration: migration 101 applies cleanly ON TOP OF a schema that stops at
 * 100, and the table it creates behaves as the publisher and the reader assume.
 *
 * WHY THIS EXISTS, sibling of `096-wallet-wrap-intents.int.test.ts`.
 * `globalSetup` runs the whole chain 001..101 in one pass on an empty database,
 * which proves the file is valid SQL and nothing more. It does NOT prove:
 *
 *   1. that the runner applies 101 as an INCREMENT to a populated schema that
 *      already stands at 100, rather than as step 101 of a fresh chain;
 *   2. that none of 101's objects already exist at 100 - a collision with a
 *      concurrent branch would show up here and nowhere else;
 *   3. that the file is idempotent when re-executed independently of
 *      `schema_version`, which is the repair/mirror path;
 *   4. that its CHECKs refuse the two rows a writer defect would produce.
 *
 * MECHANISM, unchanged from the 096 template: a second database inside the SAME
 * container the suite already runs, the real `runMigrationsWithProgress`
 * pointed at a temp directory holding only the files at or below 100, and then
 * 101 copied in and the runner invoked again. Nothing is stubbed: same runner,
 * same files, same Postgres.
 *
 * `getVexAgentMigrationsDir()` resolves the directory THE ENGINE RUNTIME loads
 * from: `dist/vex-agent/db/migrations` when built, otherwise the source tree.
 * It is NOT the desktop app's packaged mirror, which is a git-ignored artifact
 * generated by `vex-app/scripts/copy-migrations.mjs`.
 */

import { describe, it, expect, afterAll, beforeAll } from "vitest";
import { copyFileSync, mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import pg from "pg";

import { runMigrationsWithProgress } from "../../../lib/db/migrate-runner.js";
import { getVexAgentMigrationsDir } from "@utils/package-assets.js";

const SOURCE_DIR = getVexAgentMigrationsDir();
const TARGET_DB = "vex_101_probe";
const MIGRATION_101 = "101_portfolio_snapshot_groups.sql";
const TABLE = "proj_portfolio_snapshot_groups";

let pool: pg.Pool;
let stagingDir: string;

/** Migration filenames at or below `maxVersion`, by the runner's own rule. */
function filesUpTo(maxVersion: number): string[] {
  return readdirSync(SOURCE_DIR)
    .filter((f) => f.endsWith(".sql") && /^\d{3}_/.test(f))
    .filter((f) => Number.parseInt(f.slice(0, 3), 10) <= maxVersion)
    .sort();
}

async function tableExists(): Promise<boolean> {
  const res = await pool.query<{ n: string }>(
    "SELECT COUNT(*)::text AS n FROM pg_tables WHERE schemaname = 'public' AND tablename = $1",
    [TABLE],
  );
  return Number(res.rows[0]?.n ?? "0") > 0;
}

async function schemaVersion(): Promise<number> {
  const res = await pool.query<{ v: string }>(
    "SELECT COALESCE(MAX(version), 0)::text AS v FROM schema_version",
  );
  return Number(res.rows[0]?.v ?? "0");
}

async function insertGroup(fields: {
  id: string;
  settled?: string;
  inTransit?: string;
  unresolved?: number;
  inFlight?: string;
}): Promise<void> {
  await pool.query(
    `INSERT INTO ${TABLE}
       (snapshot_group_id, settled_usd, in_transit_usd, unresolved_count, in_flight)
     VALUES ($1::uuid, $2, $3, $4, $5::jsonb)`,
    [
      fields.id,
      fields.settled ?? "50",
      fields.inTransit ?? "150",
      fields.unresolved ?? 0,
      fields.inFlight ?? "[]",
    ],
  );
}

const GROUP_A = "11111111-1111-4111-8111-111111111111";
const GROUP_B = "22222222-2222-4222-8222-222222222222";

beforeAll(async () => {
  const base = process.env.VEX_DB_URL;
  if (!base) throw new Error("VEX_DB_URL is unset - globalSetup did not run.");

  const admin = new pg.Pool({ connectionString: base });
  try {
    await admin.query(`DROP DATABASE IF EXISTS ${TARGET_DB}`);
    await admin.query(`CREATE DATABASE ${TARGET_DB}`);
  } finally {
    await admin.end();
  }

  const url = new URL(base);
  url.pathname = `/${TARGET_DB}`;
  pool = new pg.Pool({ connectionString: url.toString() });

  stagingDir = mkdtempSync(path.join(tmpdir(), "vex-101-"));
}, 120_000);

afterAll(async () => {
  await pool?.end();
  if (stagingDir) rmSync(stagingDir, { recursive: true, force: true });
  const base = process.env.VEX_DB_URL;
  if (base) {
    const admin = new pg.Pool({ connectionString: base });
    try {
      await admin.query(`DROP DATABASE IF EXISTS ${TARGET_DB}`);
    } finally {
      await admin.end();
    }
  }
});

describe("migration 101 on a schema that stands at 100", () => {
  it("reaches 100 with no snapshot-group table present", async () => {
    const upTo100 = filesUpTo(100);
    for (const f of upTo100) copyFileSync(path.join(SOURCE_DIR, f), path.join(stagingDir, f));

    const result = await runMigrationsWithProgress({ pool, migrationsDir: stagingDir });

    expect(result.applied).toBe(upTo100.length);
    expect(await schemaVersion()).toBe(100);
    expect(await tableExists()).toBe(false);
  }, 180_000);

  it("applies 101 as the NEXT increment, and re-running is a no-op", async () => {
    copyFileSync(path.join(SOURCE_DIR, MIGRATION_101), path.join(stagingDir, MIGRATION_101));

    const first = await runMigrationsWithProgress({ pool, migrationsDir: stagingDir });
    expect(first.applied).toBe(1);
    expect(first.files).toEqual([MIGRATION_101]);
    expect(await schemaVersion()).toBe(101);
    expect(await tableExists()).toBe(true);

    // The RUNNER's idempotence: `schema_version` already holds 101.
    const second = await runMigrationsWithProgress({ pool, migrationsDir: stagingDir });
    expect(second.applied).toBe(0);

    // The FILE's own idempotence, independent of `schema_version`: a repair or
    // mirror path that re-executes the SQL must not fail or duplicate.
    const sql = readFileSync(path.join(SOURCE_DIR, MIGRATION_101), "utf-8");
    await expect(pool.query(sql)).resolves.toBeDefined();
  }, 180_000);

  it("leaves proj_portfolio_snapshots untouched - the change is expand-only", async () => {
    // Old code reads the per-wallet rows and nothing else. If 101 had altered
    // that table, a build that predates it would read a schema it does not know.
    const res = await pool.query<{ column_name: string }>(
      `SELECT column_name FROM information_schema.columns
        WHERE table_name = 'proj_portfolio_snapshots' ORDER BY column_name`,
    );
    const columns = res.rows.map((r) => r.column_name);
    expect(columns).toEqual(expect.arrayContaining([
      "wallet_family", "wallet_address", "snapshot_group_id", "total_usd", "pnl_vs_prev",
    ]));
    // And nothing links the two, deliberately: the per-wallet table has no
    // unique key on `snapshot_group_id` to reference.
    const fks = await pool.query<{ n: string }>(
      `SELECT COUNT(*)::text AS n FROM pg_constraint
        WHERE conrelid = $1::regclass AND contype = 'f'`,
      [TABLE],
    );
    expect(Number(fks.rows[0]?.n)).toBe(0);
  });

  it("stores one record per group and rejects a duplicate", async () => {
    await insertGroup({ id: GROUP_A });
    await expect(insertGroup({ id: GROUP_A })).rejects.toThrow();
    await insertGroup({ id: GROUP_B });

    const res = await pool.query<{ n: string }>(`SELECT COUNT(*)::text AS n FROM ${TABLE}`);
    expect(Number(res.rows[0]?.n)).toBe(2);
  });

  it("keeps NUMERIC precision on both USD columns", async () => {
    const res = await pool.query<{ settled: string; transit: string }>(
      `SELECT settled_usd::text AS settled, in_transit_usd::text AS transit
         FROM ${TABLE} WHERE snapshot_group_id = $1::uuid`,
      [GROUP_A],
    );
    expect(res.rows[0]?.settled).toBe("50");
    expect(res.rows[0]?.transit).toBe("150");
  });

  it("refuses a non-array ledger and a negative unresolved count", async () => {
    // Both are writer defects reaching durable state, and the reader would
    // render either one as a wrong figure on the user's portfolio card.
    await expect(
      insertGroup({ id: "33333333-3333-4333-8333-333333333333", inFlight: '{"not":"an array"}' }),
    ).rejects.toThrow(/in_flight_is_array/);
    await expect(
      insertGroup({ id: "44444444-4444-4444-8444-444444444444", unresolved: -1 }),
    ).rejects.toThrow(/unresolved_count_check/);
  });
});
