/**
 * The `AGENTS.md` managed block: idempotency, drift, and "the rest of the file
 * is the user's".
 *
 * The risk here is not formatting. It is that Vex silently overwrites a
 * human's edit, or silently fails to notice one. So the assertions are about
 * the DRIFT CONTRACT: the hash in the opening marker is the digest of the body
 * Vex wrote, an edited body is detected as drifted, a drifted body survives an
 * ordinary merge untouched, and only an explicit Repair replaces it.
 */

import { describe, it, expect } from "vitest";

import { STUDIO_SAFETY_PREFIX } from "@vex-agent/mcp/instructions.js";
import { STUDIO_USAGE_NOTES } from "@vex-agent/studio/instructions/shared-usage.js";
import {
  STUDIO_PROTOCOLS_DOC_PATH,
  inspectStudioManagedBlock,
  mergeStudioManagedBlock,
  removeStudioManagedBlock,
  renderStudioManagedBlock,
  renderStudioManagedBody,
  studioManagedBodyHash,
} from "@vex-agent/studio/installer/render/managed-block.js";

const USER_TEXT_BEFORE = "# Contributing\n\nRun the tests before you push.\n";
const USER_TEXT_AFTER = "\n## House style\n\nNo em dashes.\n";

function textOf(result: ReturnType<typeof mergeStudioManagedBlock>): string {
  if (result.status !== "rendered") {
    throw new Error(`expected rendered bytes, got ${result.status}`);
  }
  return result.text;
}

describe("the managed block's content", () => {
  it("reuses the safety prefix and the shared usage notes rather than restating them", () => {
    const body = renderStudioManagedBody();
    expect(body).toContain(STUDIO_SAFETY_PREFIX);
    expect(body).toContain(STUDIO_USAGE_NOTES);
  });

  it("points at the rich protocol declarations instead of inlining them", () => {
    expect(renderStudioManagedBody()).toContain(STUDIO_PROTOCOLS_DOC_PATH);
  });

  it("says it is generated and what editing it does", () => {
    expect(renderStudioManagedBody()).toContain("generated by Vex");
    expect(renderStudioManagedBody()).toContain("drift");
  });

  it("is deterministic: the same inputs give the same bytes", () => {
    expect(renderStudioManagedBlock()).toBe(renderStudioManagedBlock());
  });

  it("records the digest of its own body in the opening marker", () => {
    const block = renderStudioManagedBlock();
    const expected = studioManagedBodyHash(renderStudioManagedBody());
    expect(block.startsWith(`<!-- vex:studio:begin hash=${expected} -->\n`)).toBe(true);
    expect(block.endsWith("<!-- vex:studio:end -->\n")).toBe(true);
  });
});

describe("merging the managed block into AGENTS.md", () => {
  it("appends to a file that has none, leaving the user's text first", () => {
    const merged = textOf(mergeStudioManagedBlock(USER_TEXT_BEFORE, { overwriteDrift: false }));
    expect(merged.startsWith(USER_TEXT_BEFORE)).toBe(true);
    expect(merged).toContain(renderStudioManagedBlock());
  });

  it("creates the file content when there is none at all", () => {
    const merged = textOf(mergeStudioManagedBlock("", { overwriteDrift: false }));
    expect(merged).toBe(renderStudioManagedBlock());
  });

  it("is idempotent: merging an up-to-date file changes nothing", () => {
    const once = textOf(mergeStudioManagedBlock(USER_TEXT_BEFORE, { overwriteDrift: false }));
    expect(mergeStudioManagedBlock(once, { overwriteDrift: false }).status).toBe("unchanged");
  });

  it("replaces the block in place, preserving text on BOTH sides", () => {
    const stale = `${USER_TEXT_BEFORE}<!-- vex:studio:begin hash=${studioManagedBodyHash("old body")} -->\nold body\n<!-- vex:studio:end -->\n${USER_TEXT_AFTER}`;
    const merged = textOf(mergeStudioManagedBlock(stale, { overwriteDrift: false }));

    expect(merged.startsWith(USER_TEXT_BEFORE)).toBe(true);
    expect(merged.endsWith(USER_TEXT_AFTER)).toBe(true);
    expect(merged).not.toContain("old body");
    expect(merged).toContain(renderStudioManagedBody());
  });
});

describe("drift", () => {
  const installed = textOf(mergeStudioManagedBlock(USER_TEXT_BEFORE, { overwriteDrift: false }));
  const edited = installed.replace(
    "This project is connected to Vex",
    "This project is TOTALLY connected to Vex",
  );

  it("reports an untouched block as intact and up to date", () => {
    const state = inspectStudioManagedBlock(installed);
    expect(state).toEqual({ kind: "intact", upToDate: true });
  });

  it("reports an absent block as absent, not as drifted", () => {
    expect(inspectStudioManagedBlock(USER_TEXT_BEFORE)).toEqual({ kind: "absent" });
  });

  it("detects a human edit inside the fence", () => {
    const state = inspectStudioManagedBlock(edited);
    expect(state.kind).toBe("drifted");
    if (state.kind === "drifted") {
      expect(state.actualHash).not.toBe(state.recordedHash);
    }
  });

  it("does NOT detect an edit OUTSIDE the fence: that text is the user's", () => {
    const outsideEdited = `${installed}\n${USER_TEXT_AFTER}`;
    expect(inspectStudioManagedBlock(outsideEdited)).toEqual({ kind: "intact", upToDate: true });
  });

  it("never silently overwrites a drifted block", () => {
    expect(mergeStudioManagedBlock(edited, { overwriteDrift: false }).status).toBe("unchanged");
  });

  it("overwrites a drifted block ONLY on an explicit repair", () => {
    const repaired = textOf(mergeStudioManagedBlock(edited, { overwriteDrift: true }));
    expect(repaired).not.toContain("TOTALLY");
    expect(inspectStudioManagedBlock(repaired)).toEqual({ kind: "intact", upToDate: true });
    expect(repaired.startsWith(USER_TEXT_BEFORE)).toBe(true);
  });

  it("refuses a half-open fence instead of guessing where its region ends", () => {
    const halfOpen = `${USER_TEXT_BEFORE}<!-- vex:studio:begin hash=abc -->\nbody with no end\n`;
    const merge = mergeStudioManagedBlock(halfOpen, { overwriteDrift: true });
    expect(merge.status).toBe("refused");
    if (merge.status === "refused") expect(merge.reason).toBe("malformed_managed_block");

    const orphanEnd = `${USER_TEXT_BEFORE}<!-- vex:studio:end -->\n`;
    expect(mergeStudioManagedBlock(orphanEnd, { overwriteDrift: true }).status).toBe("refused");
  });
});

describe("removing the managed block", () => {
  it("leaves the rest of the file byte-identical", () => {
    const withBlock = textOf(mergeStudioManagedBlock(USER_TEXT_BEFORE, { overwriteDrift: false }));
    const removed = removeStudioManagedBlock(withBlock);
    expect(removed.status).toBe("rendered");
    if (removed.status === "rendered") expect(removed.text).toBe(USER_TEXT_BEFORE);
  });

  it("is a no-op when there is no block", () => {
    expect(removeStudioManagedBlock(USER_TEXT_BEFORE).status).toBe("unchanged");
  });
});
