/**
 * The `AGENTS.md` managed block: idempotency, drift, and "the rest of the file
 * is the user's".
 *
 * The risk here is not formatting. It is that Vex silently overwrites a
 * human's edit, or silently fails to notice one. So the assertions are about
 * the DRIFT CONTRACT: the hash in the opening marker is the digest of the body
 * Vex wrote, an edited body is detected as drifted, a drifted body survives an
 * ordinary merge untouched, and only an explicit Repair replaces it.
 */

import { describe, it, expect } from "vitest";

import { STUDIO_SAFETY_PREFIX } from "@vex-agent/mcp/instructions.js";
import { STUDIO_USAGE_NOTES } from "@vex-agent/studio/instructions/shared-usage.js";
import {
  STUDIO_PROTOCOLS_DOC_PATH,
  inspectStudioManagedBlock,
  mergeStudioManagedBlock,
  removeStudioManagedBlock,
  renderStudioManagedBlock,
  renderStudioManagedBody,
  studioManagedBodyHash,
} from "@vex-agent/studio/installer/render/managed-block.js";
import {
  STUDIO_CHANGE_NOTE_LIMIT,
  boundStudioChangeNotes,
} from "@vex-agent/studio/instructions/project-brief.js";
import {
  STUDIO_CLAUDE_MD_IMPORT,
  claudeMdImportsAgents,
  mergeClaudeMdImport,
  removeClaudeMdImport,
  renderFreshClaudeMd,
} from "@vex-agent/studio/installer/render/claude-md.js";
import {
  STUDIO_USAGE_AMOUNTS,
  STUDIO_USAGE_ERRORS,
  STUDIO_USAGE_FINDING_TOOLS,
  STUDIO_USAGE_UNAVAILABLE_TOOLS,
} from "@vex-agent/studio/instructions/shared-usage.js";
import { STUDIO_TEST_BRIEF } from "./render-fixtures.js";

const USER_TEXT_BEFORE = "# Contributing\n\nRun the tests before you push.\n";
const USER_TEXT_AFTER = "\n## House style\n\nNo em dashes.\n";

function textOf(result: ReturnType<typeof mergeStudioManagedBlock>): string {
  if (result.status !== "rendered") {
    throw new Error(`expected rendered bytes, got ${result.status}`);
  }
  return result.text;
}

describe("the managed block's content", () => {
  it("reuses the safety prefix and the shared usage notes rather than restating them", () => {
    const body = renderStudioManagedBody(STUDIO_TEST_BRIEF);
    expect(body).toContain(STUDIO_SAFETY_PREFIX);
    // The notes reach the block as their NAMED PARTS (the block presents them
    // under the owner's section layout), so each part is asserted verbatim.
    expect(body).toContain(STUDIO_USAGE_FINDING_TOOLS);
    expect(body).toContain(STUDIO_USAGE_AMOUNTS);
    expect(body).toContain(STUDIO_USAGE_ERRORS);
    expect(body).toContain(STUDIO_USAGE_UNAVAILABLE_TOOLS);
  });

  it("points at the rich protocol declarations instead of inlining them", () => {
    expect(renderStudioManagedBody(STUDIO_TEST_BRIEF)).toContain(STUDIO_PROTOCOLS_DOC_PATH);
  });

  it("says it is generated and what editing it does", () => {
    expect(renderStudioManagedBody(STUDIO_TEST_BRIEF)).toContain("generated by Vex");
    expect(renderStudioManagedBody(STUDIO_TEST_BRIEF)).toContain("drift");
  });

  it("is deterministic: the same inputs give the same bytes", () => {
    expect(renderStudioManagedBlock(STUDIO_TEST_BRIEF)).toBe(renderStudioManagedBlock(STUDIO_TEST_BRIEF));
  });

  it("records the digest of its own body in the opening marker", () => {
    const block = renderStudioManagedBlock(STUDIO_TEST_BRIEF);
    const expected = studioManagedBodyHash(renderStudioManagedBody(STUDIO_TEST_BRIEF));
    // The marker carries the Vex version alongside the drift hash.
    expect(
      block.startsWith(
        `<!-- vex:studio:begin vex=${STUDIO_TEST_BRIEF.vexVersion} hash=${expected} -->\n`,
      ),
    ).toBe(true);
    expect(block.endsWith("<!-- vex:studio:end -->\n")).toBe(true);
  });
});

describe("merging the managed block into AGENTS.md", () => {
  it("appends to a file that has none, leaving the user's text first", () => {
    const merged = textOf(mergeStudioManagedBlock(USER_TEXT_BEFORE, STUDIO_TEST_BRIEF, { overwriteDrift: false }));
    expect(merged.startsWith(USER_TEXT_BEFORE)).toBe(true);
    expect(merged).toContain(renderStudioManagedBlock(STUDIO_TEST_BRIEF));
  });

  it("creates the file content when there is none at all", () => {
    const merged = textOf(mergeStudioManagedBlock("", STUDIO_TEST_BRIEF, { overwriteDrift: false }));
    expect(merged).toBe(renderStudioManagedBlock(STUDIO_TEST_BRIEF));
  });

  it("is idempotent: merging an up-to-date file changes nothing", () => {
    const once = textOf(mergeStudioManagedBlock(USER_TEXT_BEFORE, STUDIO_TEST_BRIEF, { overwriteDrift: false }));
    expect(mergeStudioManagedBlock(once, STUDIO_TEST_BRIEF, { overwriteDrift: false }).status).toBe("unchanged");
  });

  it("replaces the block in place, preserving text on BOTH sides", () => {
    const stale = `${USER_TEXT_BEFORE}<!-- vex:studio:begin hash=${studioManagedBodyHash("old body")} -->\nold body\n<!-- vex:studio:end -->\n${USER_TEXT_AFTER}`;
    const merged = textOf(mergeStudioManagedBlock(stale, STUDIO_TEST_BRIEF, { overwriteDrift: false }));

    expect(merged.startsWith(USER_TEXT_BEFORE)).toBe(true);
    expect(merged.endsWith(USER_TEXT_AFTER)).toBe(true);
    expect(merged).not.toContain("old body");
    expect(merged).toContain(renderStudioManagedBody(STUDIO_TEST_BRIEF));
  });
});

describe("drift", () => {
  const installed = textOf(mergeStudioManagedBlock(USER_TEXT_BEFORE, STUDIO_TEST_BRIEF, { overwriteDrift: false }));
  const edited = installed.replace(
    "This repository is connected to Vex",
    "This repository is TOTALLY connected to Vex",
  );

  it("reports an untouched block as intact and up to date", () => {
    const state = inspectStudioManagedBlock(installed, STUDIO_TEST_BRIEF);
    expect(state).toEqual({ kind: "intact", upToDate: true });
  });

  it("reports an absent block as absent, not as drifted", () => {
    expect(inspectStudioManagedBlock(USER_TEXT_BEFORE, STUDIO_TEST_BRIEF)).toEqual({ kind: "absent" });
  });

  it("detects a human edit inside the fence", () => {
    const state = inspectStudioManagedBlock(edited, STUDIO_TEST_BRIEF);
    expect(state.kind).toBe("drifted");
    if (state.kind === "drifted") {
      expect(state.actualHash).not.toBe(state.recordedHash);
    }
  });

  it("does NOT detect an edit OUTSIDE the fence: that text is the user's", () => {
    const outsideEdited = `${installed}\n${USER_TEXT_AFTER}`;
    expect(inspectStudioManagedBlock(outsideEdited, STUDIO_TEST_BRIEF)).toEqual({ kind: "intact", upToDate: true });
  });

  it("never silently overwrites a drifted block", () => {
    expect(mergeStudioManagedBlock(edited, STUDIO_TEST_BRIEF, { overwriteDrift: false }).status).toBe("unchanged");
  });

  it("overwrites a drifted block ONLY on an explicit repair", () => {
    const repaired = textOf(mergeStudioManagedBlock(edited, STUDIO_TEST_BRIEF, { overwriteDrift: true }));
    expect(repaired).not.toContain("TOTALLY");
    expect(inspectStudioManagedBlock(repaired, STUDIO_TEST_BRIEF)).toEqual({ kind: "intact", upToDate: true });
    expect(repaired.startsWith(USER_TEXT_BEFORE)).toBe(true);
  });

  it("refuses a half-open fence instead of guessing where its region ends", () => {
    const halfOpen = `${USER_TEXT_BEFORE}<!-- vex:studio:begin hash=abc -->\nbody with no end\n`;
    const merge = mergeStudioManagedBlock(halfOpen, STUDIO_TEST_BRIEF, { overwriteDrift: true });
    expect(merge.status).toBe("refused");
    if (merge.status === "refused") expect(merge.reason).toBe("malformed_managed_block");

    const orphanEnd = `${USER_TEXT_BEFORE}<!-- vex:studio:end -->\n`;
    expect(mergeStudioManagedBlock(orphanEnd, STUDIO_TEST_BRIEF, { overwriteDrift: true }).status).toBe("refused");
  });
});

describe("removing the managed block", () => {
  it("leaves the rest of the file byte-identical", () => {
    const withBlock = textOf(mergeStudioManagedBlock(USER_TEXT_BEFORE, STUDIO_TEST_BRIEF, { overwriteDrift: false }));
    const removed = removeStudioManagedBlock(withBlock);
    expect(removed.status).toBe("rendered");
    if (removed.status === "rendered") expect(removed.text).toBe(USER_TEXT_BEFORE);
  });

  it("is a no-op when there is no block", () => {
    expect(removeStudioManagedBlock(USER_TEXT_BEFORE).status).toBe("unchanged");
  });
});

/**
 * ITEM 7b: the project-dependent half. These assertions exist because every one
 * of these facts is something an agent acts on - how many tools it can find,
 * what authority it holds, when that authority was granted, and who decides
 * whether a bug report leaves the machine.
 */
describe("the project-dependent half of the block", () => {
  const body = renderStudioManagedBody(STUDIO_TEST_BRIEF);

  it("says what the server is, that it dies with the app, and where keys live", () => {
    expect(body).toContain("LOCAL MCP server inside the Vex desktop app");
    expect(body).toContain("unreachable when the app is");
    expect(body).toContain("Private keys NEVER leave the Vex app");
    expect(body).toContain("unlocked vault");
    expect(body).toContain("registered locally");
  });

  it("tells the agent an app it builds speaks MCP to the SAME server", () => {
    expect(body).toContain("## Building applications on these tools");
    expect(body).toContain("MCP IS the API");
    expect(body).toContain("`vex-mcp` bridge command");
    expect(body).toContain("`vex-mcp`");
    expect(body).toContain("publicName");
  });

  it("says the app inherits every restriction, and that there is NO REST API", () => {
    // The load-bearing half: an agent that believes it can build a thin HTTP
    // wrapper around a wallet has just invented a door around the approval
    // card, the permission snapshot and the vault.
    expect(body).toContain("INHERITS EVERY RESTRICTION");
    expect(body).toContain("because there is no other");
    expect(body).toContain("per-call scope snapshot");
    expect(body).toContain("approval card");
    expect(body).toContain("vault-locked signing");
    expect(body).toContain("NO separate REST endpoint");
  });

  it("carries the LIVE tool counts it was given, not a pinned number", () => {
    expect(body).toContain("12 tools are ALWAYS LOADED");
    expect(body).toContain("147 protocol tools across");
    expect(body).toContain("3 protocols");
    // And the per-protocol breakdown, also live.
    expect(body).toContain("- morpho: 43");
    expect(body).toContain("- uniswap: 83");

    // The proof that they are not constants: a different inventory renders
    // different text from the same code path.
    const other = renderStudioManagedBody({
      ...STUDIO_TEST_BRIEF,
      inventory: {
        alwaysLoadedCount: 13,
        searchableCount: 200,
        protocols: [{ name: "pendle", toolCount: 200 }],
      },
    });
    expect(other).toContain("13 tools are ALWAYS LOADED");
    expect(other).toContain("200 protocol tools across");
    expect(other).toContain("- pendle: 200");
    expect(other).not.toContain("morpho");
  });

  it("puts the CHANGE LOG first, above every other section", () => {
    const changeLog = body.indexOf("## Change log (this file)");
    expect(changeLog).toBeGreaterThan(-1);
    for (const heading of [
      "## This project",
      "## Your authority",
      "## What Vex MCP is",
      "## The tool surface",
      "## Safety rules",
      "## Building applications",
      "## Reporting Vex bugs",
    ]) {
      expect(body.indexOf(heading), `${heading} must follow the change log`)
        .toBeGreaterThan(changeLog);
    }
  });

  it("renders the owner's section order exactly", () => {
    const order = [
      "# Vex Studio - project \"acme-trading\"",
      "## Change log (this file)",
      "## This project",
      "## Your authority - as of 2026-08-25",
      "## What Vex MCP is",
      "## The tool surface and how to navigate it",
      "## Safety rules",
      "## Building applications on these tools",
      "## Reporting Vex bugs (bounty)",
    ];
    const positions = order.map((heading) => body.indexOf(heading));
    expect(positions.every((position) => position > -1)).toBe(true);
    expect([...positions].sort((a, b) => a - b)).toEqual(positions);
  });

  it("names the project, its id and its configured agents", () => {
    expect(body).toContain("- Name: acme-trading");
    expect(body).toContain("- Project id: 0f6b1c2e-8a4d-4f1b-9c3e-7d5a2b8e4c10");
    expect(body).toContain("- Configured agents: Claude Code, Codex CLI");
  });

  it("says the first render is the first render, not an empty log", () => {
    const first = renderStudioManagedBody({ ...STUDIO_TEST_BRIEF, changeNotes: [] });
    expect(first).toContain("initial render for this project");
    expect(first).toContain("Vex 0.2.6");
  });

  it("reuses the shared usage notes VERBATIM rather than restating them", () => {
    // One source for the words an agent acts on: the file and the MCP handshake
    // cannot tell it two different things about units or about "declined".
    expect(body).toContain(STUDIO_USAGE_AMOUNTS);
    expect(body).toContain(STUDIO_USAGE_ERRORS);
    expect(body).toContain(STUDIO_USAGE_FINDING_TOOLS);
    expect(body).toContain(STUDIO_USAGE_UNAVAILABLE_TOOLS);
  });

  it("names the GENERIC SIGNING PAIRS by their real registry names", () => {
    // These four are why an app can sign anything the user's wallets can sign.
    // The names are the registry's own (`tools/registry/wallet-transaction.ts`);
    // an invented name here would send an agent looking for a tool that does
    // not exist and, worse, invite it to roll its own signing path.
    for (const tool of [
      "WalletEvmTransactionPrepare",
      "WalletEvmTransactionConfirm",
      "WalletSolanaTransactionPrepare",
      "WalletSolanaTransactionConfirm",
    ]) {
      expect(body, `${tool} must be named`).toContain(tool);
    }
    expect(body).toContain("signs nothing, holds no key");
    expect(body).toContain("durable intent");
    expect(body).toContain("revalidates");
    expect(body).toContain("digest binding");
    expect(body).toContain("fee caps");
  });

  it("tells the reader the file does NOT grow across Vex updates", () => {
    expect(body).toContain("THIS FILE DOES NOT GROW");
    expect(body).toContain("IN");
    expect(body).toContain("PLACE - the block is rewritten, never appended to");
    expect(body).toContain("markers is never touched");
  });

  it("tells the agent there is NO generic execute tool to invent", () => {
    expect(body).toContain("NO generic execute tool");
  });

  it("states the permission AND the wallets AND both as-of dates", () => {
    expect(body).toContain("Permission: RESTRICTED");
    expect(body).toContain("approval card");
    expect(body).toContain("0x1111111111111111111111111111111111111111");
    expect(body).toContain("So11111111111111111111111111111111111111112");
    expect(body).toContain("- Granted: 2026-08-01");
    expect(body).toContain("- Last updated: 2026-08-25");
    expect(body).toContain("read FRESH ON EVERY CALL");
  });

  it("renders the stored `full` permission as AUTONOMOUS, with its meaning", () => {
    const full = renderStudioManagedBody({ ...STUDIO_TEST_BRIEF, permission: "full" });
    expect(full).toContain("Permission: AUTONOMOUS");
    expect(full).toContain("execute immediately");
    expect(full).toContain("real money");
  });

  it("says so when no wallet is selected instead of listing nothing", () => {
    const none = renderStudioManagedBody({ ...STUDIO_TEST_BRIEF, wallets: [] });
    expect(none).toContain("Wallets: none selected");
  });

  it("lists change-log entries newest first and declares its own bound", () => {
    expect(body).toContain(`Vex keeps the last ${String(STUDIO_CHANGE_NOTE_LIMIT)} entries`);
    const newest = body.indexOf("updated the wallet selection");
    const older = body.indexOf("added the codex config");
    expect(newest).toBeGreaterThan(-1);
    expect(older).toBeGreaterThan(newest);
  });

  it("bounds the change-note list by dropping the OLDEST entries", () => {
    const many = Array.from({ length: STUDIO_CHANGE_NOTE_LIMIT + 4 }, (_, i) => ({
      version: "0.9.9",
      date: "2026-08-25",
      summary: `change ${String(i)}`,
    }));
    const bounded = boundStudioChangeNotes(many);
    expect(bounded).toHaveLength(STUDIO_CHANGE_NOTE_LIMIT);
    expect(bounded[0]?.summary).toBe("change 0");
    expect(bounded.at(-1)?.summary).toBe(`change ${String(STUDIO_CHANGE_NOTE_LIMIT - 1)}`);
  });

  it("ends with a bug-report note that ASKS and never reports on its own", () => {
    expect(body).toContain("https://github.com/Vex-Foundation/Vex");
    expect(body).toContain("USDC or VEX token");
    expect(body).toContain("Discord");
    expect(body).toContain("ASK FIRST, ALWAYS");
    expect(body).toContain("Never open a report");
  });

  it("covers the change notes and the authority WITH the drift hash", () => {
    // The whole point of putting them inside the markers: editing a change note
    // or a wallet line is drift, exactly like editing the safety prefix.
    const installed = textOf(
      mergeStudioManagedBlock("", STUDIO_TEST_BRIEF, { overwriteDrift: false }),
    );
    const tampered = installed.replace(
      "0x1111111111111111111111111111111111111111",
      "0x2222222222222222222222222222222222222222",
    );
    expect(inspectStudioManagedBlock(tampered, STUDIO_TEST_BRIEF).kind).toBe("drifted");

    const noteTampered = installed.replace("added the codex config", "did nothing");
    expect(inspectStudioManagedBlock(noteTampered, STUDIO_TEST_BRIEF).kind).toBe("drifted");
  });

  it("reports a stale block as intact but NOT up to date when the brief moves", () => {
    const installed = textOf(
      mergeStudioManagedBlock("", STUDIO_TEST_BRIEF, { overwriteDrift: false }),
    );
    const state = inspectStudioManagedBlock(installed, {
      ...STUDIO_TEST_BRIEF,
      permission: "full",
    });
    expect(state).toEqual({ kind: "intact", upToDate: false });
  });
});

describe("the CLAUDE.md import", () => {
  const USER_CLAUDE = "# My rules\n\nBe brief.\n";

  it("creates a file that imports AGENTS.md", () => {
    const fresh = renderFreshClaudeMd();
    expect(fresh.status).toBe("rendered");
    if (fresh.status === "rendered") {
      expect(claudeMdImportsAgents(fresh.text)).toBe(true);
      expect(fresh.text).toContain(STUDIO_CLAUDE_MD_IMPORT);
    }
  });

  it("appends the import to an existing file, keeping the user's text first", () => {
    const merged = mergeClaudeMdImport(USER_CLAUDE);
    expect(merged.status).toBe("rendered");
    if (merged.status === "rendered") {
      expect(merged.text.startsWith(USER_CLAUDE)).toBe(true);
      expect(claudeMdImportsAgents(merged.text)).toBe(true);
    }
  });

  it("is idempotent", () => {
    const merged = mergeClaudeMdImport(USER_CLAUDE);
    if (merged.status !== "rendered") throw new Error("expected rendered");
    expect(mergeClaudeMdImport(merged.text).status).toBe("unchanged");
  });

  it("does not mistake prose about @AGENTS.md for an import", () => {
    expect(claudeMdImportsAgents("See @AGENTS.md for the Vex section.\n")).toBe(false);
  });

  it("removes only the import line and returns the original bytes", () => {
    const merged = mergeClaudeMdImport(USER_CLAUDE);
    if (merged.status !== "rendered") throw new Error("expected rendered");
    const removed = removeClaudeMdImport(merged.text);
    expect(removed.status).toBe("rendered");
    if (removed.status === "rendered") expect(removed.text).toBe(USER_CLAUDE);
  });

  it("is a no-op to remove when there is no import", () => {
    expect(removeClaudeMdImport(USER_CLAUDE).status).toBe("unchanged");
  });
});
