import { requireValue } from "../../../../../../../src/__tests__/helpers/require-value.js";
import { useLighterAnalysisStore } from "../../../../stores/lighterAnalysisStore.js";
import { fireEvent, render, screen, cleanup } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { StudyChartApi } from "../chart-analysis-api.js";
import { ChartTools } from "../ChartTools.js";
import type { ChartCandleRow } from "../chart-adapter.js";
import { parseChartPreferences } from "../chart-preferences.js";
vi.mock("../ChartDrawings.js", () => ({ ChartDrawings: () => null }));
beforeEach(() => { localStorage.clear(); useLighterAnalysisStore.setState({ charts: {}, favorites: [] }); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.useRealTimers(); });
function setup() {
  const lines: { setData: ReturnType<typeof vi.fn>; createPriceLine: ReturnType<typeof vi.fn> }[] = [];
  const setStretchFactor = vi.fn();
  const chart = { subscribeCrosshairMove: vi.fn(), unsubscribeCrosshairMove: vi.fn(), paneSize: () => ({ width: 500, height: 300 }), takeScreenshot: vi.fn(() => ({ toBlob: (callback: (blob: Blob | null) => void) => callback(new Blob(["image"])) })), addSeries: vi.fn((_definition: unknown, _options: unknown, _pane?: number) => { const line = { setData: vi.fn(), createPriceLine: vi.fn() }; lines.push(line); return line; }), removeSeries: vi.fn(), panes: () => [0, 1, 2].map(() => ({ setStretchFactor })), timeScale: () => ({ timeToCoordinate: () => 0, coordinateToLogical: (x: number) => x, logicalToCoordinate: (x: number) => x, subscribeVisibleLogicalRangeChange: vi.fn(), unsubscribeVisibleLogicalRangeChange: vi.fn(), getVisibleLogicalRange: () => ({ from: 10, to: 40 }), setVisibleLogicalRange: vi.fn() }) };
  const rows: ChartCandleRow[] = Array.from({ length: 50 }, (_, i) => ({ timestamp: 1_700_000_000 + i * 60, open: 10 + i, close: 11 + i, high: 12 + i, low: 9 + i, volumeBase: 100, volumeQuote: 1000 }));
  const host = { current: document.createElement("div") };
  const props = { chart: chart satisfies StudyChartApi, series: null, host, rows, scope: "rhc:7", theme: "chronos", precision: 2, chartType: "candles" as const, onChartType: vi.fn(), onVolume: vi.fn(), onFills: vi.fn(), onScale: vi.fn() };
  return { chart, rows, lines, props, setStretchFactor };
}
describe("Chart analysis controls", () => {
  it("adds real independent RSI and MACD panes and removes studies cleanly", () => {
    const { chart, props, setStretchFactor, lines } = setup();
    const view = render(<ChartTools {...props} />);
    expect(chart.addSeries).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole("checkbox", { name: /RSI 14/ }));
    expect(chart.addSeries.mock.calls.at(-1)?.[2]).toBe(1);
    expect(lines.at(-1)?.createPriceLine).toHaveBeenCalledTimes(2);
    fireEvent.click(screen.getByRole("checkbox", { name: /^MACD/ }));
    expect(chart.addSeries.mock.calls.slice(-3).every(call => call[2] === 2)).toBe(true);
    expect(lines.at(-1)?.setData.mock.lastCall?.[0].length).toBeGreaterThan(0);
    expect(setStretchFactor).toHaveBeenCalledWith(3);
    expect(setStretchFactor).toHaveBeenCalledWith(1);
    view.unmount();
    expect(chart.removeSeries).toHaveBeenCalledTimes(chart.addSeries.mock.calls.length);
  });
  it("updates studies for live candles without recreating their series", () => {
    const { chart, props, rows, lines } = setup();
    const view = render(<ChartTools {...props} />);
    fireEvent.click(screen.getByRole("checkbox", { name: /SMA 20/ }));
    const before = requireValue(requireValue(lines[0]).setData.mock.lastCall)[0].at(-1).value;
    view.rerender(<ChartTools {...props} rows={rows.map((row, i) => i === 49 ? { ...row, close: row.close + 1 } : row)} />);
    expect(chart.addSeries).toHaveBeenCalledTimes(1);
    expect(requireValue(requireValue(lines[0]).setData.mock.lastCall)[0].at(-1).value).toBeCloseTo(before + .05);
  });
  it("restores validated study, volume and type preferences without leaking between markets", () => {
    const { props } = setup();
    useLighterAnalysisStore.getState().savePreferences("rhc:7", { ...parseChartPreferences(null), studies: ["ema"], volume: false, chartType: "line" });
    const view = render(<ChartTools key="rhc:7" {...props} />);
    expect((screen.getByRole("checkbox", { name: /EMA 20/ }) as HTMLInputElement).checked).toBe(true);
    expect(screen.getByRole("button", { name: "Volume" }).getAttribute("aria-pressed")).toBe("false");
    expect(props.onChartType).toHaveBeenLastCalledWith("line");
    view.rerender(<ChartTools key="core:7" {...props} scope="core:7" />);
    expect((screen.getByRole("checkbox", { name: /EMA 20/ }) as HTMLInputElement).checked).toBe(false);
    expect(props.onChartType).toHaveBeenLastCalledWith("candles");
    fireEvent.click(screen.getByRole("checkbox", { name: /SMA 20/ }));
    expect(requireValue(useLighterAnalysisStore.getState().charts["core:7"]).preferences.studies).toEqual(["sma"]);
    view.rerender(<ChartTools key="rhc:7" {...props} />);
    expect((screen.getByRole("checkbox", { name: /EMA 20/ }) as HTMLInputElement).checked).toBe(true);
    expect((screen.getByRole("checkbox", { name: /SMA 20/ }) as HTMLInputElement).checked).toBe(false);
  });
  it("applies restored volume visibility when the chart becomes ready", () => {
    const { props } = setup();
    useLighterAnalysisStore.getState().savePreferences("rhc:7", { ...parseChartPreferences(null), volume: false });
    const view = render(<ChartTools {...props} chart={null} />);
    props.onVolume.mockClear();
    view.rerender(<ChartTools {...props} />);
    expect(props.onVolume).toHaveBeenLastCalledWith(false);
  });
  it("exports the native chart image and releases the download URL", () => {
    vi.useFakeTimers();
    const { chart, props } = setup();
    const createObjectURL = vi.fn(() => "blob:chart-image"); const revokeObjectURL = vi.fn();
    vi.stubGlobal("URL", { createObjectURL, revokeObjectURL });
    const click = vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {});
    render(<ChartTools {...props} />);
    fireEvent.click(screen.getByRole("button", { name: "Save chart image without drawings" }));
    expect(chart.takeScreenshot).toHaveBeenCalledOnce();
    expect(click).toHaveBeenCalledOnce();
    expect(screen.getByRole("status").textContent).toContain("Drawings are not included");
    vi.runAllTimers();
    expect(revokeObjectURL).toHaveBeenCalledWith("blob:chart-image");
  });
  it("recomputes and relabels a study when its period changes, rejecting out-of-range input", () => {
    const { props, lines } = setup();
    render(<ChartTools {...props} />);
    fireEvent.click(screen.getByRole("checkbox", { name: /SMA 20/ }));
    const line = requireValue(lines[0]);
    expect(requireValue(line.setData.mock.lastCall)[0]).toHaveLength(31);
    fireEvent.change(screen.getByLabelText("SMA 20 period"), { target: { value: "5" } });
    expect(screen.getByRole("checkbox", { name: /SMA 5/ })).toBeTruthy();
    expect(screen.getByLabelText("Active indicators").textContent).toBe("SMA 5");
    const relabeled = requireValue(lines[lines.length - 1]);
    expect(requireValue(relabeled.setData.mock.lastCall)[0]).toHaveLength(46);
    expect(requireValue(useLighterAnalysisStore.getState().charts["rhc:7"]).preferences.periods.sma).toBe(5);
    fireEvent.change(screen.getByLabelText("SMA 5 period"), { target: { value: "0" } });
    fireEvent.change(screen.getByLabelText("SMA 5 period"), { target: { value: "501" } });
    expect(requireValue(useLighterAnalysisStore.getState().charts["rhc:7"]).preferences.periods.sma).toBe(5);
  });
  it("routes type and volume controls and closes the study disclosure with Escape", () => {
    const { props } = setup();
    render(<ChartTools {...props} />);
    expect(props.onScale).toHaveBeenLastCalledWith("linear");
    fireEvent.change(screen.getByLabelText("Chart type"), { target: { value: "line" } });
    expect(props.onChartType).toHaveBeenCalledWith("line");
    fireEvent.click(screen.getByRole("button", { name: "Volume" }));
    expect(props.onVolume).toHaveBeenLastCalledWith(false);
    expect(props.onFills).toHaveBeenLastCalledWith(true);
    fireEvent.click(screen.getByRole("button", { name: "Fills" }));
    expect(props.onFills).toHaveBeenLastCalledWith(false);
    expect(requireValue(useLighterAnalysisStore.getState().charts["rhc:7"]).preferences.fills).toBe(false);
    fireEvent.click(screen.getByRole("button", { name: "Log" }));
    expect(props.onScale).toHaveBeenLastCalledWith("log");
    expect(screen.getByRole("button", { name: "Log" }).getAttribute("aria-pressed")).toBe("true");
    expect(requireValue(useLighterAnalysisStore.getState().charts["rhc:7"]).preferences.scale).toBe("log");
    const details = requireValue(screen.getByText("Indicators").closest("details"));
    details.open = true;
    const escape = new KeyboardEvent("keydown", { key: "Escape", bubbles: true, cancelable: true });
    fireEvent(details, escape);
    expect(escape.defaultPrevented).toBe(true);
    expect(details.open).toBe(false);
  });
});
