/**
 * `.vex/protocols.md`: the RICH declarations the `AGENTS.md` managed block
 * deliberately does not carry.
 *
 * The managed block is compact because it sits inside a file every agent loads
 * on every turn. The full picture - which protocols exist, which tools each one
 * exports, which of them move funds and which environment variable a tool needs
 * - belongs in a document an agent reads when it wants it. Same split as the
 * MCP handshake string versus `tools/list`.
 *
 * GENERATED FROM THE LIVE INVENTORY, exactly like
 * `tool-surface-spec/studio-mcp/exported-tools.md`, and reviewed the same way:
 * `pnpm generate:studio-protocols-doc` writes the committed copy and
 * `--check` fails CI when it drifts. A project's `.vex/protocols.md` is a copy
 * of these bytes, so the committed artifact IS what agents read.
 *
 * Descriptions are NOT reproduced here, for the same reason the exported-tools
 * doc omits them: the registry is their one home, and copying 159 of them into
 * a Markdown file would create a second, immediately stale source for the text
 * a model acts on. Nothing is cut - what is omitted is named, and the whole
 * description is always available from `tools/list`.
 */

import { buildStudioInventory } from "../../mcp/inventory/index.js";
import type { StudioTool } from "../../mcp/inventory/types.js";

/** Escape the only character that can break a Markdown table row. */
function cell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

function toolRow(tool: StudioTool): string {
  return [
    "",
    cell(tool.publicName),
    cell(tool.title),
    tool.annotations.readOnlyHint ? "read-only" : "mutating",
    tool.annotations.destructiveHint ? "yes" : "no",
    tool.requiresEnv ?? "-",
    "",
  ].join(" | ").trim();
}

const TABLE_HEADER = [
  "| tool | title | access | destructive | requires env |",
  "| --- | --- | --- | --- | --- |",
];

export function renderStudioProtocolsDoc(): string {
  const inventory = buildStudioInventory();
  const internal = inventory.filter((tool) => tool.kind === "internal");
  const protocol = inventory.filter((tool) => tool.kind === "protocol");
  const namespaces = [...new Set(protocol.map((tool) => tool.namespace ?? ""))];

  const lines: string[] = [
    "# Vex protocols and tools",
    "",
    "GENERATED BY VEX on project creation, written into your project as",
    "`.vex/protocols.md`, and refreshed on every Vex update. Do not edit it by",
    "hand: the next refresh overwrites it.",
    "",
    "## What this file is, and what it is not",
    "",
    "This is the INVENTORY: every tool the `vex` MCP server has, with its",
    "read-only and destructive hints and the environment variable it needs. It",
    "carries no argument contracts and no descriptions, by design - each tool's",
    "own description in `tools/list` is their single home, and `vex_ToolDescribe`",
    "returns one whole.",
    "",
    "Every tool below is in `tools/list` and there is no activation step ON THE",
    "SERVER. Call each one by the name YOUR CLIENT shows for it (Claude Code:",
    "`mcp__vex__<publicName>`) and load a deferred schema the way your client",
    "does. Call `vex_ToolSearch` (read-only, runs nothing) when you know what you",
    "want to do but not which tool does it.",
    "",
    "One `vex_ToolSearch` query answer is bounded and there is no cursor:",
    "`totalCount` says how many tools matched and `hasMore` says whether the",
    "answer left any out. Rows it left out are not unreachable - narrow instead,",
    "either by passing `namespace` alone to list one protocol in full, or by",
    "asking a tighter query. The full table below is the other route: every tool",
    "this server has is listed here.",
    "",
    "`access` is the MCP `readOnlyHint`. `destructive` is the MCP",
    "`destructiveHint`: it marks the tools that broadcast a user-wallet",
    "transaction or otherwise cause an irreversible effect. THOSE are the calls",
    "the approval card gates - a mutating tool that is not destructive, such as a",
    "local database write, raises no card. In a restricted project a destructive",
    "call BLOCKS until the user answers the card in Vex, and the result you",
    "receive is the settled outcome: executed, declined, expired, refused or",
    "unknown. Never call it twice, and never retry an unknown outcome.",
    "",
    "`requires env` names an environment variable the tool needs. It is metadata",
    "only: an unmet variable is answered at call time with a typed",
    "`configuration_unavailable` result naming the variable and the remedy.",
    "",
    "Argument contracts and units are on each tool's own description in",
    "`tools/list`, which is their single home; `vex_ToolDescribe` returns one",
    "whole, including a description your client truncated. Units are PER FIELD -",
    "human decimals or raw smallest units - so read the field description and",
    "never guess. AGENTS.md in this project carries the rest of the protocol: the",
    "permission level in force, the outcome vocabulary, the Vex fee and the task",
    "shapes.",
    "",
    "## Totals",
    "",
    `- tools: ${String(inventory.length)}`,
    `- Vex tools: ${String(internal.length)}`,
    `- protocol tools: ${String(protocol.length)} across ${String(namespaces.length)} protocols`,
    `- destructive: ${String(inventory.filter((t) => t.annotations.destructiveHint).length)}`,
    "",
    "## Vex tools",
    "",
    ...TABLE_HEADER,
    ...internal.map(toolRow),
    "",
    "## Protocols",
    "",
  ];

  for (const namespace of namespaces) {
    lines.push(
      `### ${namespace}`,
      "",
      ...TABLE_HEADER,
      ...protocol.filter((tool) => tool.namespace === namespace).map(toolRow),
      "",
    );
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
