/**
 * Memory v2 — `memory_candidates` Zod boundary schema (S1b).
 *
 * Validates the agent-facing `MemorySuggest` payload (wired in S2) and
 * defines the immutable-evidence-anchor + provenance shapes the repo persists.
 * This stage DEFINES + TESTS the schema; S2 wires it into the handler.
 *
 * Two security-critical, strict, bounded sub-schemas:
 *
 * - `evidenceRefsSchema` (FIX-1). Evidence anchors reference the IMMUTABLE
 *   audit trail — `protocol_executions.id` / `protocol_capture_items.id` plus
 *   semantic keys (`instrumentKey` / `positionKey`). They NEVER reference
 *   `proj_*` SERIALs (those are TRUNCATEd + regenerated by sync/replay, so they
 *   are unstable). `.strict()` rejects any unknown key (e.g. a `proj_*`-style
 *   id field) at the boundary.
 *
 * - `sourceRefsSchema` (MF3). `source_refs` is general provenance and S2 makes
 *   it agent-adjacent, so it MUST be strict, bounded, and POINTER-ONLY — never
 *   a loose bag (`z.record(z.unknown())` is forbidden). It carries only
 *   `messageIds` (current-session message ids) and `toolCallIds` (bounded
 *   token ids), system-captured at the suggest boundary. Free-text, extra keys,
 *   and non-pointer payloads are rejected.
 *
 * `kind` reuses the shared `isValidKind` regex (`knowledge/policy.ts`) — open
 * snake_case, NOT an enum — matching `knowledge_entries.kind`.
 *
 * Pure module: Zod schemas + derived types. No DB, no embeddings, no I/O. The
 * embedding, system source tier, status, and content_hash are NOT in the agent
 * input schema — they are set by the suggest boundary / repo (memory-system-v2
 * §6: the manager never trusts an agent-supplied `source`), so they live on the
 * repo's `InsertCandidateInput` (db/repos/memory-candidates/types.ts), not here.
 */

import { z } from "zod";

import { isValidKind, MAX_KIND_LENGTH } from "@vex-agent/knowledge/policy.js";

// ── Bounds (named so the contract is explicit and reused by tests) ──

/** Max title length accepted at the suggest boundary. */
export const CANDIDATE_TITLE_MAX = 512;
/** Max summary length (1-3 sentences; embedding input together with title). */
export const CANDIDATE_SUMMARY_MAX = 4000;
/** Max content_md length stored verbatim. */
export const CANDIDATE_CONTENT_MD_MAX = 100_000;
/** Max length of a single entity / tag token. */
export const CANDIDATE_TAG_MAX = 128;
export const CANDIDATE_ENTITY_MAX = 256;
/** Max number of entities / tags. */
export const CANDIDATE_ENTITIES_MAX = 64;
export const CANDIDATE_TAGS_MAX = 64;
/** Max number of immutable evidence anchors per candidate. */
export const CANDIDATE_EVIDENCE_REFS_MAX = 32;
/** Max number of pointer refs per source_refs array. */
export const CANDIDATE_SOURCE_REFS_MAX = 64;
/** Max length of a semantic evidence key (instrumentKey / positionKey). */
export const CANDIDATE_SEMANTIC_KEY_MAX = 256;

// ── Evidence anchors (FIX-1 — immutable audit-trail ids only) ───────

/**
 * One immutable evidence anchor. `executionId` (protocol_executions.id) is
 * REQUIRED; the optional fields narrow to a specific capture item / instrument /
 * position. `.strict()` rejects any other key — including `proj_*` projection
 * ids, which are unstable across sync/replay and must never be anchored on.
 */
export const evidenceAnchorSchema = z
  .object({
    executionId: z.number().int().positive(),
    captureItemId: z.number().int().positive().optional(),
    instrumentKey: z.string().min(1).max(CANDIDATE_SEMANTIC_KEY_MAX).optional(),
    positionKey: z.string().min(1).max(CANDIDATE_SEMANTIC_KEY_MAX).optional(),
  })
  .strict();

export type EvidenceAnchor = z.infer<typeof evidenceAnchorSchema>;

/** Bounded array of immutable evidence anchors (FIX-1). */
export const evidenceRefsSchema = z.array(evidenceAnchorSchema).max(CANDIDATE_EVIDENCE_REFS_MAX);

export type EvidenceRefs = z.infer<typeof evidenceRefsSchema>;

// ── Source refs (MF3 — strict, bounded, pointer-only provenance) ────

/**
 * Pointer-only provenance, system-captured at the S2 suggest boundary from the
 * current session. `messageIds` are `messages.id` integers; `toolCallIds` are
 * bounded id tokens (provider tool-call ids). `.strict()` + no free-text field
 * means the agent can never inject arbitrary provenance text or extra keys.
 */
export const sourceRefsSchema = z
  .object({
    messageIds: z.array(z.number().int().positive()).max(CANDIDATE_SOURCE_REFS_MAX).optional(),
    toolCallIds: z
      .array(z.string().regex(/^[A-Za-z0-9._:-]{1,128}$/))
      .max(CANDIDATE_SOURCE_REFS_MAX)
      .optional(),
  })
  .strict();

export type SourceRefs = z.infer<typeof sourceRefsSchema>;

// ── Agent suggest input (validated by MemorySuggest in S2) ────

/**
 * The shape `MemorySuggest` validates in S2. Defined now so the repo's
 * `InsertCandidateInput` (types.ts) can reuse the derived sub-types and so the
 * boundary contract is testable in S1b. `.strict()` rejects unknown agent keys.
 *
 * Deliberately ABSENT (system-set, not agent-supplied — memory-system-v2 §6):
 * `embedding` / `embeddingModel` / `embeddingDim` (computed after redaction at
 * the suggest boundary), `source` provenance tier (manager-derived, never
 * trusted from the agent), `status` (DB default 'pending'), `content_hash`
 * (computed by the boundary), `proposedBy` / `sensitivity` /
 * `evidenceStrength` / `retrievalVisibility` (system-classified), and the
 * `recordedAt` / `availableAtDecisionTime` point-in-time boundaries (system).
 */
export const candidateSuggestInputSchema = z
  .object({
    kind: z
      .string()
      .max(MAX_KIND_LENGTH)
      .refine((v) => isValidKind(v), {
        message:
          "kind must be snake_case ASCII (a-z, 0-9, _), start with a letter, max 64 chars",
      }),
    title: z.string().min(1).max(CANDIDATE_TITLE_MAX),
    summary: z.string().min(1).max(CANDIDATE_SUMMARY_MAX),
    contentMd: z.string().max(CANDIDATE_CONTENT_MD_MAX).default(""),
    entities: z.array(z.string().min(1).max(CANDIDATE_ENTITY_MAX)).max(CANDIDATE_ENTITIES_MAX).default([]),
    tags: z.array(z.string().min(1).max(CANDIDATE_TAG_MAX)).max(CANDIDATE_TAGS_MAX).default([]),
    sourceRefs: sourceRefsSchema.default({}),
    evidenceRefs: evidenceRefsSchema.default([]),
    confidence: z.number().min(0).max(1).optional(),
    importance: z.number().int().min(1).max(10).default(5),
    // Point-in-time annotations the agent may legitimately supply (ISO 8601).
    // The system-only as-of boundary (availableAtDecisionTime) and ingestion
    // time (recordedAt) are NOT here — they are stamped by the boundary / repo.
    eventTime: z.iso.datetime().optional(),
    observedAt: z.iso.datetime().optional(),
  })
  .strict();

export type CandidateSuggestInput = z.infer<typeof candidateSuggestInputSchema>;
